### ISSUE TITLE
cluster bootstrap

### ISSUE THREAD

**Issue by ghost** [infochimps-labs/ironfan#1]
Hi, I'm new to chef and certainly cluster_chef, so I may have a basic misunderstanding...

When I run "knife cluster launch demohadoop master --bootstrap", it starts an EC2 instance, but that instance appears to have nothing installed on it. My understanding was that some chef specific stuff was supposed to land out there and even if it didn't install correctly, I could "manually" fire up the chef client from the EC2 instance to do the install. Looks like not even chef-client is being installed. What am I missing?

**Comment by mrflip** [comment]
Hmm.  It should follow the launch of the machine by ssh'ing in and then running the chef bootstrap script. Did you symlink the bootstrap scripts as well as the knife cluster commands into the system knife dir? Does it raise any sort of error?

Try running

```
knife cluster bootstrap demohadoop master  public.ip.address.of.the.machine
```

which should do everything the boostrap stage was supposed to.
