### ISSUE TITLE
fog can fail to create tags (fixed, see link)

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#101]
Fixed in fog in https://github.com/fog/fog/pull/730.  This was a major painpoint for me.  Once that's in a released version would it be worthwhile to use that as a minimum version in the cluster_chef-knife.gemspec?

**Comment by pcn** [comment]
I believe this has been released.  Can you update your dependency to 1.2.0?

**Comment by temujin9** [comment]
It'll take a little while for this to get cut into the gem itself.
