### ISSUE TITLE
Require server slice params in knife commands be a single commandline arg

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#104]
I'd like to kill the ability to say 
    knife cluster foo nikko scraper 1-7
instead only accepting the server slice as a single commandline parameter
    knife cluster foo nikko-scraper-1-7  
    knife cluster foo "nikko scraper 1-7" 
    knife cluster foo nikko-scraper
    knife cluster foo "nikko scraper"

Right now `knife cluster ssh` only accepts the latter, and the same for `knife cluster vagrant`.

Not knowing the arity of commandline args leads to screwy/ambiguous logic for identifying the slice, is hard to document, and has made it hard to provide good error messages.

I'll make it deprecated behavior on the non-vagrant non-ssh commands -- the only non-named args they take are the server slices; given multiple params they will complain loudly but then grudgingly join them with dashes and carry on.

**Comment by temujin9** [comment]
This has been implemented; closing.
