### ISSUE TITLE
Existing security group permissions cause needless warnings

### ISSUE THREAD

**Issue by dhruvbansal** [infochimps-labs/ironfan#108]
Whenever I do security group authorizations in a cluster definition file, I see (after the very first knife run) warning messages like

```
WARNING: InvalidPermission.Duplicate => The permission '19762327-1-1-65535' has already been authorized on the specified group
```

I think these are automatically inserted b/c of a `begin...rescue` block that is farting out the messages of whatever errors it's rescuing from.  That logic should be smart enough to **not** complain when the caught error is something like this.

I bet there are other places this happens, too, I just notice it here.

**Comment by mrflip** [comment]
Given that the call's purpose is to idempotently establish the group's
existence it makes sense to swallow that exception, we can make that fix.

Is your account ID entered as the numeric one, or an alias?  If the latter,
it won't ever match security groups. Your cluster launch commands will
always be a few api latencies slower, but that's on you.

flip

On Tue, Feb 21, 2012 at 3:39 PM, Dhruv Bansal <
reply@reply.github.com

> wrote:
> 
> Whenever I do security group authorizations in a cluster definition file,
> I see (after the very first knife run) warning messages like
> 
> ```
> WARNING: InvalidPermission.Duplicate => The permission
> '19762327-1-1-65535' has already been authorized on the specified group
> ```
> 
> I think these are automatically inserted b/c of a `begin...rescue`
> block that is farting out the messages of whatever errors it's rescuing
> from.  That logic should be smart enough to **not** complain when the
> caught error is something like this.
> 
> I bet there are other places this happens, too, I just notice it here.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps-labs/ironfan/issues/108

## 

infochimps.com - discover data

**Comment by pcn** [comment]
I think I've mentioned this in the past - I would prefer that this gets properly reflected with an INFO message that "This group already exists".  I don't exactly know how to do it, though, because the exception that bubbles up is of a class that doesn't seem to be in scope, so I haven't had any luck in catching the exception by type.  Chalk this up to my lack of strong ruby knowledge.

**Comment by mrflip** [comment]
For a 'security group has already been authorized' error, just does a log.debug message. Other errors still get a ui.warn. 

Closing.
