### ISSUE TITLE
Cannot find knife config file

### ISSUE THREAD

**Issue by mattmcclean** [infochimps-labs/ironfan#111]
Am trying to get Ironfan working on my MacBook Pro with Mac OSX 10.7.3 and ironfan (3.1.4).

I followed the installation instructions from the wiki including setting up the homebase dir from git clone command. I also set env parameters in .bash_profile including CHEF_HOMEBASE, CHEF_USER & CHEF_ORGANIZATION.

Am getting the following error message:

```
MacBookPro:homebase matt$ knife cluster list
WARNING: No knife configuration file found
WARNING: No cluster path set. Taking a wild guess that ["/var/chef/clusters"] is 
reasonable based on your cookbook_path -- but please set cluster_path in your knife.rb
Cluster Path: /var/chef/clusters
```

Any hints to how I can debug this problem?

**Comment by temujin9** [comment]
Can you pull the latest version of the homebase into yours? The commands 
`git add remote upstream https://github.com/infochimps-labs/ironfan-homebase.git`
`git pull upstream master`
should manage it.

It looks like you're using some slightly outdated instructions, too. You should check the latest version; you want to remove some or all of the environmental parameters, as they may be superfluous now (and/or overriding correct defaults with incorrect values).

**Comment by mattmcclean** [comment]
Unfortuntately I get the same problem. I did a `git pull` command as I did not fork the repo and the following changes were made since the initial clone: 

```
commit 9f56d656c5ac27b686d3fa76978e18ff1aa3d462
Author: Nathaniel Eliot <temujin9@t9productions.com>
Date:   Mon Mar 5 03:11:56 2012 -0600

Updating notes and pantry

diff --git a/notes b/notes
index 59bba36..3c290b8 160000
--- a/notes
+++ b/notes
@@ -1 +1 @@
-Subproject commit 59bba365c8d80624febcc8d1fabbe32284a6153c
+Subproject commit 3c290b8680e9278e915c6819bf2ea645338e53fe
diff --git a/vendor/ironfan-pantry b/vendor/ironfan-pantry
index d5b3246..a06db8f 160000
--- a/vendor/ironfan-pantry
+++ b/vendor/ironfan-pantry
@@ -1 +1 @@
-Subproject commit d5b3246ff48666092f2c6475a2b1e03af66e4f1c
+Subproject commit a06db8f467e20c2021c0abe88bc04f954d04875b
```

**Comment by temujin9** [comment]
What is your CHEF_HOMEBASE set to, or have you unset it already? It should be set to wherever your homebase repository actually is.

**Comment by temujin9** [comment]
Are you still experiencing this issue? If so, could you please rerun with -VV, and dump the results into a comment here, so I can help you debug further?

**Comment by temujin9** [comment]
No response in a month: presume problem is fixed, closing.
