### ISSUE TITLE
Modifying users and running processes

### ISSUE THREAD

**Issue by dhruvbansal** [infochimps-labs/ironfan#112]
The following trouble can occur:

1) `daemon_user` definition sets up a user 'foo' with home directory `node[:foo][:data_dir]`
2) `volumes` recipes haven't run yet so `node[:foo][:data_dir]` is empty; 'foo' user's home directory gets set to /var/run/foo or similar
3) chef client completes, resulting in several running processes owned by the 'foo' user
4) next chef-client run, `node[:foo][:data_dir]` is non-empty as volumes ran on the last chef-client run
5) an attempt is now made to modify the 'foo' user's home directory but fails horribly b/c 'foo' user has running processes.

What's the fix?

**Comment by temujin9** [comment]
I think the fix is make sure that `volumes` runs before everything else. Right now, the `:first` keyword in the cluster definition is probably your best bet.

**Comment by temujin9** [comment]
@mrflip says to reference https://github.com/infochimps-labs/ironfan/wiki/design_notes-cookbook_event_ordering for more information on event ordering.

**Comment by temujin9** [comment]
@dhruvbansal: Has this managed to ameliorate the problem you were having, or do we need to do a deeper dive?

**Comment by dhruvbansal** [comment]
I haven't seen it come up again.

**Comment by temujin9** [comment]
Closing as fixed; reopen if it recurs.
