### ISSUE TITLE
flume recipe - ironfanhood upgrade

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#113]
Updated the flume recipe to have more ironfan-ity:
- now creates a flume user with a stable uid (325). THIS MAY CRASH CHEF if you run it on a node with an already-running chef process. Manually stop all running flume services and then `sudo usermod -u '325' flume`
- the `data_dir` uses `volume_dirs` rather than a hard-coded path. This means data is now filed in `/mnt/flume/data` as is the ironfan convention. I left flume have its way after that, meaning data is buffered to `/mnt/flume/data/$USER/agent`, `/mnt/flume/data/$USER/collector` and `/mnt/flume/data/$USER/zk`
- logs are written to `/var/log/flume/agent` and `/var/log/flume/master`, and are now named for the machine: `flume-flume-node-weatherlight-collector-0.log` and so forth.
- flume is now launched using runit not an init script. 
  - the daemons are now `flume_agent` (not `flume-node`) and `flume_master` (not `flume-master`)
- moved config file writing to `config_files.rb` -- for most multi-component cookbooks it's important that templates live in their own recipe, executed last. Fixed a hard-coded path in there too.
- library no longer `require 'right_aws'`'s until needed, which means there's time to install it. Still shouldn't be mixed in with everything though.

Dhruv/Travis I'mma let you finish converging the machines tomorrow -- only weatherlight-collector-0 is in the new world.

/cc @temujin9 @dhruvbansal @kornypoet

**Comment by temujin9** [comment]
This has been included into mainline: closing.
