### ISSUE TITLE
Ironfan-3.1.4 -- undefined method `realdirpath' for File:Class (NoMethodError)

### ISSUE THREAD

**Issue by jessehu** [infochimps-labs/ironfan#114]
Hello!   Does Ironfan requires Ruby 1.9+ ? Didn't find a note saying Ironfan requires Ruby 1.9.

I use Ruby 1.8.7 and ClusterChef, everything works fine.  But  Ruby 1.8.7 and Ironfan-3.1.4 give this error: 

ironfan-homebase apple$ knife cluster list
/Library/Ruby/Gems/1.8/gems/ironfan-3.1.4/lib/chef/knife/cluster_bootstrap.rb:19: undefined method `realdirpath' for File:Class (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/knife/core/subcommand_loader.rb:37:in`load'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/knife/core/subcommand_loader.rb:37:in`each'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/knife/core/subcommand_loader.rb:37:in `load_commands'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/knife.rb:112:in`load_commands'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/knife.rb:160:in `run'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/lib/chef/application/knife.rb:128:in`run'
    from /Library/Ruby/Gems/1.8/gems/chef-0.10.8/bin/knife:25
    from /usr/bin/knife:19:in `load'
    from /usr/bin/knife:19

**Comment by mrflip** [comment]
### regarding 1.8:
- there's nothing essentially 1.9 in ironfan
- when the new DslObject shows up it may be 1.9 only, not sure yet.
- our current test coverage is unfortunately poor on the knife tools, and we don't use 1.9 in production at all. I am very interested in expanded test coverage, but awaiting that we can't really offer anything more than a "worksforme" to 1.8 users

So, this might not be the last 1.8 bug, but I have no problem accepting patches as long as they don't lead to soupy code or reduced functionality in the main branch. (I'm totally fine with soupy workarounds that are held in a completely separate lib that is fenced off to only run in 1.8)

### regarding realdirpath:

Does Pathname have that method in 1.8? Is there a compatibility lib you can include, or a monkeypatch that we can selectively include in 1.8?

This one seems inessential, so I don't mind removing it; it made life a bit easier while developing to let me hijack the scripts directory.

Make sure to make the parallel change across all the `chef/knife/*.rb` scripts

There's also a realdirpath in `homebase/knife/knife.rb`, which I'd like to keep -- it's what lets you symlink a ~/.chef directory.

**Comment by jessehu** [comment]
Hi Flip,  Thanks for your quick feedback.

I tried on Ruby 1.8.7, The following Pathname sample code works well. It should also work on 1.8.6 and 1.9+.  See also Pathname doc (http://ruby-doc.org/stdlib-1.8.7/libdoc/pathname/rdoc/Pathname.html#method-i-realpath)

> ```
> require 'pathname'
> path = Pathname.new(File.dirname(__FILE__))
> path.realpath  # give the real dir path (symlinks are resloved)
> ```

Here is the difference between ClusterChef code and Ironfan code regarding the 'File.realdirpath' :

> ironfan/lib/chef/knife/cluster_bootstrap.rb:require File.expand_path('ironfan_script', File.dirname(File.realdirpath(**FILE**)))
> cluster_chef/lib/cluster_chef/knife/cluster_bootstrap.rb:require File.expand_path(File.dirname(**FILE**)+"/generic_command.rb")

The cluster_chef code works very well when I use knife cluster commands to control cluster_chef.  So this code might be kept unchanged in Ironfan.   If we really need File.realdirpath,  we can use Pathname.realpath instead (which works on Ruby 1.8.7 and 1.9)

Thanks!.

**Comment by pcn** [comment]
Flip, 

In https://github.com/infochimps-labs/ironfan/issues/80 I was told that 1.9 was needed for cluster_chef 3 based on some aspect-related code that relied on the 1.9 calling convention for define_method().  Has ironfan now changed so this isn't needed anymore?

**Comment by temujin9** [comment]
We've had some internal back-and-forth about what versions we should officially support, which has solidified to:
Nobody at Infochimps uses 1.8 internally, and we lack a full test framework to ameliorate that. Therefore, we don't officially support Ruby 1.8, although we will happily accept pull requests aimed at keeping Ironfan working there as well.

(Peter: Sorry the shifting policy caused confusion. I don't anticipate any further shifts on this particular front.)

To determine if a particular bug is due to running under 1.8, get 1.9 installed alongside, run commands using `ruby1.9 -S $command` and compare. You may need to `ruby1.9 -S gem install` and/or `ruby1.9 -S bundle install` to get gems set up correctly.

**Comment by jessehu** [comment]
Thanks!  I think I will move to Ruby 1.9.x for using Ironfan.
