### ISSUE TITLE
"knife cluster launch" will cause the screen to scroll

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#117]
While it's waiting, "knife cluster launch" seems to cause the screen to scroll while it's counting the seconds until a node responds to ssh.  This seems to happen when the width of the cluster status table is wider than the window it's displayed in.

**Comment by temujin9** [comment]
That's caused by a minor bug in Formatador, which I've issued a pull request to fix: https://github.com/geemus/formatador/pull/8 . I'm going to close the issue here, as there's nothing to fix in Ironfan itself.
