### ISSUE TITLE
Confused with knife/credentials and knife/{oraganization}-credentials

### ISSUE THREAD

**Issue by rberger** [infochimps-labs/ironfan#118]
Is it expected to have both

```
    $CHEF_HOMEBASE/knife/credentials/
```

AND

```
    $CHEF_HOMEBASE/knife/$CHEF_ORGANIZATION-credentials/
```

The wiki page https://github.com/infochimps-labs/ironfan/wiki/INSTALL seems to be saying that, but its not making sense to me and the instructions seem inconsitent about it.

Credentials paths are referred in several different ways in just a few paragraphs making it a bit murkey:

```
    knife/{organization}-credentials/
    knife/credentials/
    {credentials_path}/
```

**Comment by rberger** [comment]
From looking at the knife.rb it looks like it should just be `knife/credentials` and no `knife/{organization}-credentials/`

**Comment by temujin9** [comment]
`knife/credentials` is the canonical path. For a while we were experimenting with multi-org homebases, which is why we have the `knife/{organization}-credentials` reference. I've corrected the INSTALL docco; thanks for pointing out the confusion.
