### ISSUE TITLE
Java cookbook: Oracle install broken

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#119]
Sez Brian,

> Oracle now requires you click a checkbox to download any software. Worse, that checkbox requires javascript. This means that automating downloading directly from the site requires something heavyweight like watir-webdriver
> 
> You can work around this by downloading the tarball to a local server or S3 bucket than then overriding the  attribute like this  or in a role
> 
> ```
> node['java'][jdk']['6']['x86_64']['url'] = 'http://your_local_server/java_tarball.tar.gz'
> ```

We currently use install_flavor = sun, which uses some guy's PPA. 

The oracle install comes from Opscode's cookbooks, so we should track whatever fix they put in.

**Comment by temujin9** [comment]
This should be fixed by https://github.com/infochimps-labs/opscode_cookbooks/commit/94f32415a37442747ed0d167bc0100b1b239e44f - it is a major change in the way we install, so we'll be walking it into the rest of the environment slowly.

**Comment by temujin9** [comment]
This has been largely walked into the current architecture. Closing.
