### ISSUE TITLE
Converge on right NTP cookbook

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#12]
there are two versions of the NTP cookbook in play, one from infochimps and one from librato... unless there's a reason it should be modified, can we go with the opscode-cookbooks version, placed into cookbooks/ntp ??

(I haven't looked carefully at either branch, so don't know the differences, hoping you can sort it out Nathan)

**Comment by howech** [comment]
I wrote the infochimps version - it does nothing except to install the ntp debian package. There is an opscode version is quite a bit more sophisticated, so I am perfectly happy to just go with it.

**Comment by mrflip** [comment]
+1 use the other one

On Mon, Jun 6, 2011 at 4:50 PM, howech <
reply@reply.github.com>wrote:

> I wrote the infochimps version - it does nothing except to install the ntp
> debian package. There is an opscode version is quite a bit more
> sophisticated, so I am perfectly happy to just go with it.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/12#comment_1312169

## 

infochimps.com - discover data

**Comment by mheffner** [comment]
Imported the Opscode one here: https://github.com/librato/cluster_chef/commit/1611b707972a360b7f91549d739749cf91d30c62
