### ISSUE TITLE
metachef/libraries/attr_struct.rb SyntaxError

### ISSUE THREAD

**Issue by ghost** [infochimps-labs/ironfan#122]
I am trying to use hadoop_cluster, getting following error when running chef-client. Ruby version is 1.9.2+ on client:

client$ sudo chef-client
[Sat, 17 Mar 2012 19:10:53 +0000] INFO: **\* Chef 0.10.8 ***
[Sat, 17 Mar 2012 19:10:55 +0000] INFO: Run List is [recipe[hadoop_cluster]]
[Sat, 17 Mar 2012 19:10:55 +0000] INFO: Run List expands to [hadoop_cluster]
[Sat, 17 Mar 2012 19:10:55 +0000] INFO: Starting Chef Run for hadoop
[Sat, 17 Mar 2012 19:10:55 +0000] INFO: Running start handlers
[Sat, 17 Mar 2012 19:10:55 +0000] INFO: Start handlers complete.
[Sat, 17 Mar 2012 19:10:56 +0000] INFO: Loading cookbooks [apt, dashpot, hadoop_cluster, java, metachef, runit, tuning, volumes, xfs]
[Sat, 17 Mar 2012 19:10:56 +0000] ERROR: Running exception handlers
[Sat, 17 Mar 2012 19:10:56 +0000] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[Sat, 17 Mar 2012 19:10:56 +0000] ERROR: Exception handlers complete
[Sat, 17 Mar 2012 19:10:56 +0000] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[Sat, 17 Mar 2012 19:10:56 +0000] FATAL: SyntaxError: /var/chef/cache/cookbooks/metachef/libraries/attr_struct.rb:21: syntax error, unexpected '=', expecting '|'
        define_method(name) do |val=nil|
                                    ^
/var/chef/cache/cookbooks/metachef/libraries/attr_struct.rb:160: syntax error, unexpected kEND, expecting $end
ubuntu@ip-10-122-230-143:~$ ruby --version
ruby 1.9.2p290 (2011-07-09 revision 32553) [i686-linux]

**Comment by temujin9** [comment]
Metachef got renamed to silverware a little while back; it looks like you have some outdated cookbooks. Make sure you've pulled the most recent code, and reopen this ticket if the problem persists.

**Comment by openreserach** [comment]
same issue, using hadoop_cluster's dependencies (e.g., silverware) from 
https://github.com/infochimps-labs/ironfan-pantry/tree/master/cookbooks 
when it is available, and use the rest dependencies (e.g. apt) from http://community.opscode.com/

$cat /var/chef/cache/chef-stacktrace.out
Generated at Sat Apr 07 18:46:03 +0000 2012
SyntaxError: /var/chef/cache/cookbooks/silverware/libraries/attr_struct.rb:21: syntax error, unexpected '=', expecting '|'
        define_method(name) do |val=nil|
                                    ^
/var/chef/cache/cookbooks/silverware/libraries/attr_struct.rb:164: syntax error, unexpected kEND, expecting $end
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in`require'
/var/chef/cache/cookbooks/silverware/libraries/silverware.rb:9
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:82:in `load'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:82:in`load_libraries'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:120:in `call'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:120:in`foreach_cookbook_load_segment'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:119:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:119:in`foreach_cookbook_load_segment'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:117:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:117:in`foreach_cookbook_load_segment'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:80:in `load_libraries'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/run_context.rb:57:in`load'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:195:in `setup_run_context'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/client.rb:159:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:239:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in`loop'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application/client.rb:229:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/../lib/chef/application.rb:67:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.8/bin/chef-client:26
/usr/bin/chef-client:19:in `load'

**Comment by temujin9** [comment]
I notice that your backtrace is using ruby1.8 on the client side. Can you try running it through 1.9, and see if the problem continues?

**Comment by openreserach** [comment]
Nathaniel,

I did use ruby/rubygems-1.9.1 & chef-0.10.8 in my previous result on client
@ ubuntu 11.10. However, the error still shows
/var/lib/gems/1.8/gems/....
and there is no /var/lib/gems/1.9 directory being created. What should I do
to have it tested with 1.9+? Please advise.

Thanks

-Qiming

On Sat, Apr 7, 2012 at 3:05 PM, Nathaniel Eliot <
reply@reply.github.com

**Comment by temujin9** [comment]
To test with 1.9, run commands prefixed with `ruby1.9 -S`. You may need to run `gem install` and/or `bundle install` before everything will work correctly. Please let me know if this doesn't work in ameliorating your problem.

**Comment by openreserach** [comment]
temujin9,

Could you be more specific, or point me to existing document of using ruby 1.9?
Is it required on client or workstation, or both? my client is provisioned by 
knife <cloud> server create ......
If it is required on clients, and let's assume I can manually upgrade ruby on each and every client (default is 1.8), will following be sufficient?
ln -s /user/bin/ruby1.9.1 /user/bin/ruby
Edit knife to have  #!/usr/bin/ruby -S
Edit chef-client to have #!/usr/bin/ruby -S
Doing so, I am getting errors like
$sudo chef-client
/usr/lib/ruby/1.9.1/rubygems.rb:762:in `report_activate_error': Could not find RubyGem chef (>= 0) (Gem::LoadError)
        from /usr/lib/ruby/1.9.1/rubygems.rb:219:in`activate'
        from /usr/lib/ruby/1.9.1/rubygems.rb:1065:in `gem'
        from /usr/bin/chef-client:18:in`<main>'

Do I have to run "gem install" on each client? manually? and how?. If so, will that defeat the purpose of using hadoop_cluster for automatic provisioning? Please advise.

**Comment by mrflip** [comment]
@openreserach 

The ruby version is typically chosen at bootstrap. You should be able to have `knife server create` prescribe a ruby 1.9.2+, (either by OS version: ubuntu oneiric and above are 1.9.2+; or by installing directly).  The `knife cluster launch --bootstrap` / `knife cluster bootstrap` commands use our customized bootstrap script, which installs 1.9.2 by default. Those scripts have to be used with ironfan, though (they expect some variables to be set that `knife cluster create` doesn't know about).

If at all possible, rather than debug a machine that was bootstrapped to 1.8 ruby, I would use `knife server` or `knife cluster` to make yourself a 1.9.2+ machine, convince yourself that everything works, and then backport the existing machines.

---

If you are stuck debugging the old machines:
1. remove any other copy of chef: `/path/to/old/ruby -S gem uninstall ohai chef knife`.
2. check that your new version of ruby is newer enough: running your new ruby with the `--version` should show `1.9.2-p136` or newer. `1.9.1` anything and `1.9.2-p0` are no good.

Next, instead of what you describe do something more like

```
sudo ruby1.9.1 -S gem install  --no-rdoc --no-ri ohai chef knife 
sudo ruby1.9.1 -S chef-client
```

You should not have to edit anything in the knife command. Each ruby version maintains its own set of gems, and prefixing with the 'ruby1.9.1 -S' ensures that it uses executables corresponding to that version's gems.  

(And as you hopefully conquer the frustration of this version soup, know that it's nowhere nearly as bad as the [goatrope of hadoop version numbers](http://www.cloudera.com/blog/2012/04/apache-hadoop-versions-looking-ahead-3/), where version 0.23 is later than version 1.0)

**Comment by temujin9** [comment]
@openreserach: has Flip's explanation helped you get around the Ruby versioning issue you seemed to be experiencing here? Can we close this ticket?

**Comment by openreserach** [comment]
I did upgrade to ruby1.9.3 on Ubuntu 12.04. Old issue seems to be gone, but
getting new error like:
[Sat, 12 May 2012 20:44:06 +0000] INFO: Forcing cloudera distro to
'maverick' (your machine is 'precise')
[Sat, 12 May 2012 20:44:06 +0000] ERROR: Running exception handlers
[Sat, 12 May 2012 20:44:06 +0000] FATAL: Saving node information to
/var/chef/cache/failed-run-data.json
[Sat, 12 May 2012 20:44:06 +0000] ERROR: Exception handlers complete
[Sat, 12 May 2012 20:44:06 +0000] FATAL: Stacktrace dumped to
/var/chef/cache/chef-stacktrace.out
[Sat, 12 May 2012 20:44:06 +0000] FATAL: NoMethodError: undefined method
`[]' for nil:NilClass

Generated at 2012-05-12 20:44:06 +0000
NoMethodError: undefined method `[]' for nil:NilClass
/var/chef/cache/cookbooks/volumes/definitions/volume_dirs.rb:76:in`block
(2 levels) in from_file'
/var/chef/cache/cookbooks/volumes/definitions/volume_dirs.rb:76:in `map'
/var/chef/cache/cookbooks/volumes/definitions/volume_dirs.rb:76:in`block
in from_file'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/recipe_definition_dsl_core.rb:50:in
`instance_eval'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/recipe_definition_dsl_core.rb:50:in
`method_missing'
/var/chef/cache/cookbooks/hadoop_cluster/recipes/default.rb:104:in
`from_file'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/from_file.rb:30:in
`instance_eval'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/from_file.rb:30:in
`from_file'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/cookbook_version.rb:578:in
`load_recipe'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/language_include_recipe.rb:40:in
`block in include_recipe'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/language_include_recipe.rb:27:in
`each'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/language_include_recipe.rb:27:in
`include_recipe'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/run_context.rb:72:in
`block in load'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/run_context.rb:69:in
`each'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/run_context.rb:69:in
`load'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:195:in
`setup_run_context'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/client.rb:159:in
`run'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application/client.rb:239:in
`block in run_application'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application/client.rb:229:in
`loop'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application/client.rb:229:in
`run_application'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/application.rb:67:in
`run'
/opt/opscode/embedded/lib/ruby/gems/1.9.1/gems/chef-0.10.8/bin/chef-client:26:in
`<top (required)>'
/usr/bin/chef-client:19:in`load'
/usr/bin/chef-client:19:in `<main>'

On Mon, May 14, 2012 at 11:08 AM, Nathaniel Eliot <
reply@reply.github.com

> wrote:
> 
> @openreserach: has Flip's explanation helped you get around the Ruby
> versioning issue you seemed to be experiencing here? Can we close this
> ticket?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps-labs/ironfan/issues/122#issuecomment-5692457

## 

Dr. Qiming He
Qiming.He@openresearchinc.com
301-525-6612 (Phone)
815-327-2122 (Fax)

**Comment by temujin9** [comment]
Looks like the error there may be a missing mount_point definition in a volume info. The top error _/var/chef/cache/cookbooks/volumes/definitions/volume_dirs.rb:76_ is the clue; opening the file in question finds:
`paths  = volumes.map{|vol, vol_info| ::File.expand_path(sub_path, vol_info[:mount_point]) }`

Closing this as fixed. If this second problem is not resolved with a proper mount_point, please open a ticket specific to that issue, rather than recycling this one.
