### ISSUE TITLE
Ubuntu 11.10 missing dependencies

### ISSUE THREAD

**Issue by UncleTallest** [infochimps-labs/ironfan#124]
Under vanilla Ubuntu 11.10, two dependencies need to be installed before installing the ironfan gem. 

Solution -

In the Ironfan installation docs, replace the follwing:

<code>
sudo gem install ironfan
</code>

with this:
<code>
sudo apt-get install libxml2-dev
sudo apt-get install libxslt1-dev
sudo gem install ironfan
</code>

With this minor change, Iironfan happily installs for me without a problem.

**Comment by temujin9** [comment]
https://github.com/infochimps-labs/ironfan/wiki/INSTALL now lists the need to install those two libraries. Thanks.
