### ISSUE TITLE
Exceptions running infochimps flume cookbook to setup a master

### ISSUE THREAD

**Issue by timgasper** [infochimps-labs/ironfan#125]
$ chef-client --version
Chef: 0.10.8

$ uname -a
Linux 12040 2.6.32-38-server #83-Ubuntu SMP Wed Jan 4 11:26:59 UTC 2012
x86_64 GNU/Linux

I am running infochimps flume cookbook (
https://github.com/infochimps-cookbooks/flume/) to setup a master using
flume['master'] and getting:

DEBUG: Sending HTTP Request via GET to 192.168.33.10:4000/search/node
INFO: HTTP Request Returned 400 Bad Request: invalid search query:
'announces:-flume-master' Parse error at offset: 9 Reason: Expected one of
AND, OR, NOT, ?, \, ", (, [, { at line 1, column 11 (byte 11) after :
WARN: No node announced for '-flume-master'

DEBUG: Sending HTTP Request via GET to 192.168.33.10:4000/search/node
INFO: HTTP Request Returned 400 Bad Request: invalid search query:
'announces:-zookeeper-server' Parse error at offset: 9 Reason: Expected one
of AND, OR, NOT, ?, \, ", (, [, { at line 1, column 11 (byte 11) after :
WARN: No node announced for '-zookeeper-server'

This is unfortunate as it leads to:

DEBUG: Re-raising exception: NoMethodError - undefined method `[]' for
nil:NilClass
/srv/chef/file_store/cookbooks/flume/recipes/default.rb:50:in`block in
from_file'
/opt/ruby/lib/ruby/gems/1.9.1/gems/chef-0.10.8/lib/chef/mixin/recipe_definition_dsl_core.rb:69:in
`instance_eval'

There is no flume pre-installed before running flume['master'] as above.

How to fix it?

**Comment by mrflip** [comment]
somehow your machine has come to life with no cluster name associated. Where it should be looking for a "announces:my_cluster-flume-master" it is looking for "announces:-flume-master".

You need to make sure that very early in the node's lifecycle (we do it in the client.rb) that

```
node[:cluster_name]
node[:facet_name]
node[:facet_index]
```

are set
