### ISSUE TITLE
Document Ruby 1.9 dependency

### ISSUE THREAD

**Issue by temujin9** [infochimps-labs/ironfan#127]
Nobody at Infochimps uses 1.8 internally, and we lack a full test framework to ameliorate that. Therefore, we don't officially support Ruby 1.8, although we will happily accept pull requests aimed at keeping Ironfan working there as well.

Not 100% sure where this should end up; probably in the README. @mrflip, please chime in if you have other suggestions.

**Comment by mrflip** [comment]
Updated the READMEs; closing.

To anyone who wants to port: 
- `define_method` in `ironfan-pantry/cookbooks/silverware`: 1.9 allows default and block parameters to a block. You'll have to change this to the string form of `class_eval`, calling `def`.
- `realdirpath` in the knife.rb
- I don't think there are occurrences of new-style hashes, BasicObject, or any assumptions that a hash is ordered.
