### ISSUE TITLE
minidash thttpd dependancy in ubuntu 12.04

### ISSUE THREAD

**Issue by jasherai** [infochimps-labs/ironfan#128]
FYI:

I know this is early, but thttpd has been deleted from the ubuntu archives in Precise Pangolin. As this will be a LTS release, I'm sure people will be looking at moving to it soonish.

**Comment by mrflip** [comment]
easy enough fix ( infochimps-labs/ironfan-pantry@0a2da935ef64aeb782c49ccd110dc06bf9f9d219 ) by replacing with busybox -- this is better, as it doesn't even need a special install.

I changed the port to be at 5678 (from 6789) because otherwise the daemon replacement craps the bed.
