### ISSUE TITLE
chef bootstrap fails for burninator-trogdor

### ISSUE THREAD

**Issue by dmuir** [infochimps-labs/ironfan#129]
Following the instructions in the wiki for building an ironfan ready AMI, chef bootstrapping fails on the trogdor facet.  Here's what I suspect are the relevant parts from the logs -- if you'd like more I can provide.  Just let me know.  This is from a repo cloned about a week ago.

ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] INFO: Processing gem_package[i18n] action install (package_set::default line 41)
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] INFO: package[openjdk-6-jdk] sending create action to ruby_block[update-java-alternatives](delayed)
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] INFO: Processing ruby_block[update-java-alternatives] action create (java::openjdk line 42)
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] ERROR: ruby_block[update-java-alternatives](java::openjdk line 42) has had an error
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] ERROR: Running exception handlers
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] ERROR: Exception handlers complete
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
ec2-174-129-185-162.compute-1.amazonaws.com [Tue, 17 Apr 2012 07:13:56 +0000] FATAL: TypeError: ruby_block[update-java-alternatives](java::openjdk line 42) had an error: TypeError: can't convert nil into String
ec2-174-129-185-162.compute-1.amazonaws.com Chef bootstrap failed!

**Comment by temujin9** [comment]
It looks like an attribute might not have been set correctly in choosing the openjdk version of java; did you specify the version explicitly, or did it come in as a default?

Try running the bootstrap with -VV, and seeing if the stacktrace for that TypeError is illuminating.

**Comment by dmuir** [comment]
I didn't specify openjdk explicitly at all -- my guess is it's being included by one of the other recipes in the trogdor facet (maybe one of the package sets?).

I'll try to run with -VV and see if that is illuminating.

Thanks.

**Comment by dmuir** [comment]
-VV didn't really help much.  I did notice a stack trace on the trogdor instance.  It appears that ultimately what's happening is this line in cookbooks/java/recipes/openjdk.rb is failing (returning nil):

jdk_home = Dir.glob("#{java_home_parent}/java_#{version}_openjdk?{,#{arch}}")[0]

Poking around with irb on the instance, it appears that it is the ?{,#{arch}} part of the glob that is causing it to not match.  The contents of the /usr/lib/jvm directory are:
java-6-openjdk
java-1.6.0-openjdk
java-6-sun-1.6.0.26

**Comment by temujin9** [comment]
It's brought in by the java cookbook, though I'd have to dig to find what ultimately sources that for trogdor.

We explicitly set our java to use Sun's release (for compatibility with other packages), so unfortunately the default behavior isn't as well-tested. It's probably a mistaken assumption (attribute foo is set) that should be easy to correct once located.

**Comment by temujin9** [comment]
Ah, good eye. My guess is the `?` after the openjdk isn't matching the any one character it wants at the end of the filename. Try pushing it inside the optional brackets, like so: `{,?#{arch}}`.

If you can put together a patch you've found to work, I'll gladly merge it in.

**Comment by dmuir** [comment]
I'm not a Rubyist, but from the docs, it doesn't appear that ? would be allowed inside a {} in a glob.  Replacing the ? with a \* worked fine for me, but may be too permissive.  If that's not OK, I think we may need to change the glob to a regexp.

**Comment by temujin9** [comment]
No, that's fine: it shouldn't match against anything invalid, given the rest of the glob. Check that in and get me a pull request.

**Comment by dmuir** [comment]
Not sure how to do a pull request (relatively new to GitHub) -- the fix is in the vendor/opscode module (a git submodule) which wasn't actually forked.  Is the correct thing to fork the submodule, apply the patch to the fork, then send the pull request?

**Comment by temujin9** [comment]
Fixed by https://github.com/infochimps-labs/opscode_cookbooks/commit/2695532b26644b60795d7ada341d8e37d4b7445b - thanks again.
