### ISSUE TITLE
Add facet.choose_by_index([array]) to let me cycle AZs, etc

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#13]
For launching by correct availability zone (related to @librato 's SHA:fe7a1fd37f694a8104364eeb6fe868020b22dd3b), we need a method lets me hand a facet an array like `%w[ us-east-1a us-east-1b us-east-1c ]`, to have it choose from the array based on its facet_index mod the length.

**Comment by mheffner** [comment]
To support multiple instance facets and still cycle the multiple instances through the AZs, you'll also need to use the instance index within the facet.

**Comment by howech** [comment]
You can now do this using the server object. For example

``` ruby
cluster "x" do
  use :defaults

  facet "y" do
    instances 20
    instances.times do |idx| 
     server idx do
       cloud.availability_zones = [ ["us-east-1a","us-east-1b","us-east-1c","us-east-1d"][ idx % 4] ]
     end
   end
end
```
