### ISSUE TITLE
"knife cluster kill <cluster> --kill-bogus" doesn't work

### ISSUE THREAD

**Issue by agentgonzo** [infochimps-labs/ironfan#131]
the --kill-bogus switch in cluster_kill.rb sets the :kill_bogus variable, but this isn't used anywhere so --kill-bogus does nothing and there is no way to kill bogus nodes in a cluster without doing it manually or killing the whole cluster and re-launching it.

My ruby isn't good enough to write a fix for this - sorry.

**Comment by mrflip** [comment]
I thought this was a quickie one-liner, but I'm having trouble recreating. (There is something inconsistent with the bogosity decision -- but from my end it's that it lets me kill too _many_ things.)

Can you let me know what kind of  bogosity it's reporting? If you copy-paste the contents of `knife cluster show` (XXX out any identifiers) that will tell me.

**Comment by agentgonzo** [comment]
It was a simple test - I changed the sandbox to have 2 instances, then started the cluster. Then set it back to have 1 instance and did a 'knife cluster sync sandbox-simple'. 

```
$ knife cluster show sandbox-simple

Inventorying servers in sandbox cluster, simple facet, all servers
  +------------------+-------+---------+------------+----------------+--------------+-----------------+----------+------------+-----+----------------------+
  | Name             | Chef? | State   | InstanceID | Public IP      | Private IP   | Created At      | Flavor   | AZ         | Env | Bogus                |
  +------------------+-------+---------+------------+----------------+--------------+-----------------+----------+------------+-----+----------------------+
  | sandbox-simple-0 | yes   | running | xxxxxxxxxx | xxxxxxxxxxxxx  | xxxxxxxxxxxx | 20120419-170000 | m1.small | eu-west-1a | dev |                      |
  | sandbox-simple-1 | yes   | running | xxxxxxxxxx | xxxxxxxxxxxxxx | xxxxxxxxxxx  | 20120419-170000 | m1.small | eu-west-1a |     | not_defined_in_facet |
  +------------------+-------+---------+------------+----------------+--------------+-----------------+----------+------------+-----+----------------------+
```

Then ...

```
$ knife cluster kill sandbox-simple --kill-bogus
...
Bogus servers detected: ["sandbox-simple-1"]
Running kill on sandbox-simple-0 and sandbox-simple-1...
Are you absolutely certain that you want to delete 2 chef nodes and 2 fog servers? (Type 'Yes' to confirm)
```
