### ISSUE TITLE
Support Ubuntu 12.04

### ISSUE THREAD

**Issue by dmuir** [infochimps-labs/ironfan#135]
I'm guessing this is already on the roadmap.  Is there a timeframe?  Is using the 11.10 bootstrap files likely to work in the meantime?

**Comment by temujin9** [comment]
There isn't a concrete time frame yet, but it's definitely on the road map. I would speculate a month or two before we officially support it. I believe that the differences should be minimal as far as bootstrap is concerned; if you want to dive into it in the mean-time, I'll gladly accept any patches that come from it.

**Comment by nickmarden** [comment]
FWIW, I believe that Chef 0.10.14 has an Ubuntu 12.04 bootstrap script built in: 

https://github.com/opscode/chef/blob/master/chef/lib/chef/knife/bootstrap/ubuntu12.04-gems.erb

**Comment by nickmarden** [comment]
I've submitted https://github.com/infochimps-labs/ironfan/pull/171 as a proposed bootstrap script. It differs from the 11.10 bootstrap script in that it uses the Chef-provided Ruby environment in /opt/ruby rather than trying to make sense of Ubuntu's treatment of Chef and Ruby 1.9.x

**Comment by temujin9** [comment]
As I said on the pull request, hidden requirements have become apparent:

1) It needs to build Ruby 1.9 (preferably v1.9.2-p290) from source.
2) It needs to install chef via Rubygems.

Again, sorry for that. (On the plus side, the code for the rest means that fixing this just became that much easier.)

**Comment by nickmarden** [comment]
Duly noted. See my comments on #171 about how this might be rectified in a way that makes the existing official ubuntu10.04 &ubuntu11.10 bootstrap scripts consistent with each other.

**Comment by temujin9** [comment]
We've got an internal need for this, and I've got a little space, so it's happening. Will you be free for some light testing?

**Comment by nickmarden** [comment]
Absolutely!

**Comment by temujin9** [comment]
After much ado: https://github.com/infochimps-labs/ironfan/blob/master/lib/chef/knife/bootstrap/ubuntu12.04-ironfan.erb

@nickmarden - This should look fairly familiar to you. (We tried your way, it worked, and I convinced people it was saner than the prior way.) Try it out, let me know if you find anything egregiously wrong about it.

**Comment by nickmarden** [comment]
Do we really want to symlink the OpsCode-provided Ruby into /usr/bin? That seems that it could cause a lot of surprises.

If it actually is a good idea, it would probably be better be handled by update-alternatives(8)...I think.

**Comment by temujin9** [comment]
It's a calculated risk: omnibus ruby is pretty provably reliable, especially compared with scratch-built. It turns out, however, that I want to be including their source folder in the path, instead (so that binstubs from things like bundler work right). I'll hold off on update-alternatives until/unless lesser solutions don't work; from prior experience, that can be a pretty large pile to wade through.

(See cabc900502ccb9b4190df40e790a3f4156f68ed9 for more details.)
