### ISSUE TITLE
Naive "bundle exec rake spec" fails. Is there a trick to run properly?

### ISSUE THREAD

**Issue by rberger** [infochimps-labs/ironfan#137]
I did the following:

```
rvm ruby-1.9.3@ironfan
git clone https://github.com/infochimps-labs/ironfan.git 
bundle install
bundle exec rake spec
....
33 examples, 28 failures
```

Gist of full error output: https://gist.github.com/2779803

One obvious thing was that there was no clusters directory and no cluster definition for webserver_demo.rb  or monkeyballs.rb but there were a few other seemingly non-missing file issues.

Wondering if this _should_ work or if there are some steps I'm just missing.. Wanted to know that the tests passed before I tried playing with the knife cluster code a bit...

**Comment by temujin9** [comment]
Rake specs are broken, and need to be reworked to reflect v4. It was, unfortunately, one of the corners I cut for expedience in the refactor. The specs for v3 are likewise broken, but are unlikely to be fixed. Let me know if that adversely affects things you're doing.

**Comment by temujin9** [comment]
We've got some very lightweight specs in v4.1.1, mostly just covering the DSL interpretation right now. There are two specs currently failing; I wanted to document #158, and prevent regression once we fix it.

**Comment by temujin9** [comment]
And thanks to @fractaloop for tackling this as quickly as he did.
