### ISSUE TITLE
infochimps-homebase Gemfile points to private infochimps repository

### ISSUE THREAD

**Issue by sarcasmo** [infochimps-labs/ironfan#138]
In the infochimps-homebase git repository, the Gemfile's "development" group points to infochimp's private github repo for the "guard-chef" gem, causing "bundle install" to fail for public folks. Changing line 39 from:

  gem 'guard-chef',    :git => 'git@github.com:infochimps-forks/guard-chef.git'

to:

  gem 'guard-chef',    :git => 'git://github.com/infochimps-forks/guard-chef.git'

solves the problem.

**Comment by temujin9** [comment]
Fixed [here](https://github.com/infochimps-labs/ironfan-homebase/commit/306a6e2822bc8b566d63ea01ade598d1a7d70d60); thanks. (FYI: submitting bug fixes as pull requests will get them into the code-base quicker.)
