### ISSUE TITLE
Omnibus plan for landing version_2 => Master

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#14]
These are the planned changes we will make to move the version_2 branch into production and actually release as v2.0.
# High Priority:
## H-1.   20+ Node Cluster Launch

Cluster Chef 2 should be able to handle a timely cluster launch that involves 20 or more nodes at the same time with no intervention from the user. (It currently does not do so efficiently, as all of the nodes are launched in series, also old Broham occasionally has a spaz attack and assigns two nodes the same identity).
## H-2. New Purpose Assigner (aka Patty)

Replace old Broham... Patty Bernstein showed Navin R. Johnson (Steve Martin's character in The Jerk) what his special purpose was. Exact requirements for this are still evolving in conversations between me and Nathan, but whatever it is, it needs to be able to ensure that requirement 1 does its thing.
## H-3. "Cloud SSH" equivalent

a user should be able to execute a command locally like "knife cluster ssh sudo sv restart hadoop-0.20-datanode" and expect it to run the command on every one of the machines in the cluster.
## H-4. Unified recipes

at the end of the cluster chef 2 project, we should have just one set of chef recipes in the cluster chef repo
## H-5. Virgin AMI Bootstrapping

"knife cluster launch xxxx yyyy" should work even if the cluster in question uses stock AMIs.
## H-6. Don't use AWS user data to pass DNA in

bootstrapping dna data should not be inserted into the AWS instance userdata. It should go through another mechanism - perhaps scp to the node file system as a part of the bootstrap.
## H-7. Keep Jacob happy

while we are developing, Jacob should be able to set up chimpmark using poolparty. When we are done, Jacob should be able to set up chimpmark using cluster chef 2, with a minimum amount of retooling.
# Medium Priority:
## M-1. Idempotent Cluster Start

if you say "knife cluster launch xxx yyy; knife cluster launch xxx yyy" you should end up with one set of yyy-faceted nodes in the xxx cluster (not two).
## M-2. Spot pricing

you should be able to specify spot priced nodes in the cluster definition.
## M-3 Cluster Visibility Tool

there should be a command like "knife cluster show" which will give a report on what the cluster is defined to be, what nodes exist in chef and what nodes are part of the cluster as reported by AWS.
## M-4 Use chef 0.10

although setting up chef environments is not a part of this phase of the project, we should pave the way as much as possible by ensuring that our internal clients are on version 0.10. (All clients on chef 0.10 is a requirement for chef environments to work...)

Low Priority:
## L-1 Elastic IP Assignment

probably as a chef recipe akin to the ebs volume assignment stuff
## EMR compatibility

Investigate using chef with EMR.

Project Milestones
## Major

Be able to start the Bonobo hadoop cluster as a throwaway hadoop workhorse.  Once this is accomplished, we can ensure that there is only one version of all the cookbooks and then start getting users within the company working with cluster chef 2 and getting rid of pool party.
## Minor

TBD

**Comment by howech** [comment]
I checked in some code this morning that makes "knife cloud show CLUSTER" work. Basically, cluster-chef now pre-computes from the cluster definition the values that were previously generated by the "purpose assigner". When you have a 5 node facet, it basically knows ahead of time that the nodes are going to be called "cluster-facet-x" where x is a number from 0 to 4. Based on this knowledge, as a part of the cluster.resolve! method, cluster_chef goes to both fog and chef to try to figure out the current state of the cluster, and map the existing instances/nodes into facets.  "knife cluster show CLUSTER" will give you a breakdown of all of the servers that are supposed to participate in the cluster, reporting node_name, facet and index, whether or not the node is present in chef, and the id and status of an instance running the node according to fog.

Currently, knife cluster show relies on the terminal-table gem. It doesn't entirely work, so it will probably be replaced by something else.

**Comment by mrflip** [comment]
-1 for spending too much time formatting -- propose eg

  "%-35s\t%d\t..." % [hostname, index, ...]

so that it lines up OK in the default case and gives parseable output.

flip

On Thu, May 19, 2011 at 9:50 AM, howech <
reply@reply.github.com>wrote:

> I checked in some code this morning that makes "knife cloud show CLUSTER"
> work. Basically, cluster-chef now pre-computes from the cluster definition
> the values that were previously generated by the "purpose assigner". When
> you have a 5 node facet, it basically knows ahead of time that the nodes are
> going to be called "cluster-facet-x" where x is a number from 0 to 4. Based
> on this knowledge, as a part of the cluster.resolve! method, cluster_chef
> goes to both fog and chef to try to figure out the current state of the
> cluster, and map the existing instances/nodes into facets.  "knife cluster
> show CLUSTER" will give you a breakdown of all of the servers that are
> supposed to participate in the cluster, reporting node_name, facet and
> index, whether or not the node is present in chef, and the id and status of
> an instance running the node according to fog.
> 
> Currently, knife cluster show relies on the terminal-table gem. It doesn't
> entirely work, so it will probably be replaced by something else.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/14#comment_1203889

## 

infochimps.com - discover data

**Comment by howech** [comment]
Oops, I didn't mean to close this.

**Comment by howech** [comment]
Status report:

H-1. 20+ node cluster launch:  I used "knife cluster launch" to start a 26 node cluster this afternoon. The "knife cluster launch" command took about 2 minutes to complete. It was another 3 minutes or so before "knife cluster show" was reporting that all of the nodes were registered with chef.

H-2. The "purpose assigner" has been entirely integrated into cluster chef.

H-3. Cloud SSH.  Not yet done. You can get pretty close to what you might want with plain old "knife ssh", but knife cluster ssh could still be nice as it could unequivocally locate cluster facets, where node searching can sometimes be hit or miss.

H-4 Unified recipes - not sure where this is at the moment

H-5 Virgin AMI booting - havnt done anything in particular on this yet.

H-6 AWS user data bootstrapping - TBD

H-7  I talked with Jacob this afternoon, and he seemed to be happy.

M-1 Idempotent cluster start -  there is a timespan of a couple of minutes between launching a cluster and the nodes registering with chef where a second cluster launch would do non-itempotent things, but other than that, knife cluster launch is well behaved.  If you delete nodes or reshape your cluster definition it will (expand) the cluster to meet the definition. (If you need to contract a cluster, knife node kill --no-defined --undefined will probably do what you want)

M-2 Spot pricing. Not done.

M-3 Cluster visibility tool.  Knife cluster show does a pretty good job. It might be nice to have ways to look in more detail at particular node/fog server attributes, but it should be pretty easy to add more when we figure out what we want to see.

M-4 chef-10 - knife cluster launch, knife cluster kill and knife cluster show all work under chef 0.10.0. Not sure if all of the recipes will work under chef-client version 0.10.0...

**Comment by howech** [comment]
I just implemented "knife cluster ssh". It works much like "knife ssh", only you tell it "cluster [facet [index]]" instead of a search spec.  Also, I added the ability to launch a cssh session.

I also added a lockout into cluster launch to prevent you from launching nodes in a cluster when there are "undefined" servers hanging around. You can bypass the safety with --force.

**Comment by howech** [comment]
This morning, I merged version_2 into master. (Woo hoo!).  Hopefully I didn't break too much, but some caution is probably warrented, especially around the merged master/version_2 site recipes.
