### ISSUE TITLE
knife cluster ssh <command> always returns 0 even on failure

### ISSUE THREAD

**Issue by agentgonzo** [infochimps-labs/ironfan#143]
As per the title, knife cluster ssh commands will always return 0 as if they have succeeded, even if they fail on the host. It would be much better if the return code of the running process was propagated back to knife and returned from there. This causes further problems because ssh is used implicitly by 'kick' and thus 'bootstrap' and thus ultimately 'launch', so if you have an automated process to do any of ssh/kick/bootstrap/launch and it fails when trying to run an ssh command (or chef-client) then you cannot tell this from the return code.

Obviously it is compounded by the fact that the ssh command can do multiple nodes in a cluster/facet, but returning non-zero on any failure (even if it's just hardcoded to 1 or the first exit-code to fail) would be better than 0

**Comment by temujin9** [comment]
@mrflip fixed this, and I've pulled it into the multicloud branch, which will become v3.2.0 shortly.

**Comment by agentgonzo** [comment]
Many thanks! :-)
