### ISSUE TITLE
can't use 64-bit medium instances (or 32-bit of any other size

### ISSUE THREAD

**Issue by lastobelus** [infochimps-labs/ironfan#147]
in FLAVOR_INFO in lib/ironfan/cloud.rb the medium instances are set to 32-bit and all other instance sizes are set to 64-bit.

No way is provided to override this in the cluster definition.

**Comment by mrflip** [comment]
@lastobelus let us know if #163 fixes this for you so we can close

**Comment by temujin9** [comment]
FYI: #163 has been pulled into v4.1.0, so you can just test against that.

**Comment by temujin9** [comment]
@lastobelus Assuming that the above fix plus no response in a month means the problem is solved for you; closing for now, please reopen if we haven't solved the problem.
