### ISSUE TITLE
make this a knife plugin (but retain v0.9.x compatibility)

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#15]
@rberger has proposed to make this a knife plugin -- +1

But we need to retain v0.9.x compatibility for at least a while -- It's OK if it continues to require a kludge no worse than what we have now, but does need to stay plausible with 0.9.x

**Comment by howech** [comment]
I fixed a couple of places where cluster_chef was using blank?, which for some reason doesn't work in out of the box chef-0.10.0. With that done, if you are running chef 10, you should be able to link xxx/cluster_chef/lib/cluster_chef/knife to your ~/.chef/plugins/knife directory and the chef plugins will work (knife cluster launch, knife cluster show and knife cluster kill at least...)

To get it to work as a "rubygem" plugin, we are going to have to 1) set up cluster chef as a gem, and 2) move lib/cluster_chef/knife to lib/chef/knife (within the cluster_chef gem). Then, when the gem is installed, chef will automagically discover its plugins.

**Comment by mrflip** [comment]
note for future readers: if you symlink `{path/to}/cluster_chef/lib/cluster_chef/knife` to `~/.chef/plugins/knife`, and 
 `{path/to}/cluster_chef/lib/cluster_chef/knife/bootstrap` to `~/.chef/bootstrap`, then knife picks up the plugins just fine.

**Comment by mrflip** [comment]
The pull request #59 makes this so you don't even have to do symlinks.
