### ISSUE TITLE
Spreading servers across AZs

### ISSUE THREAD

**Issue by meekmichael** [infochimps-labs/ironfan#155]
For our clusters (web applications and databases), we prefer to have our servers spread out across EC2 Availability Zones.   I understand that this may not be ideal for other workloads (big data analysis, etc).

Right now, Ironfan always sticks our servers into the first AZ in cloud.availability_zones.  Is support for having the servers allocated differently forthcoming?

I'm currently using a monkeypatch like this to accomplish this:

```
module Ironfan                                                                                                                                                                    
  class Server                                                                                                                                                                    
    def default_availability_zone                                                                                                                                                 
      offset_number = "{self.cluster_name}#{self.facet_name}".split('').inject(0) { |x,y| x += y.ord }                                                                                                                                                                                  
      self.cloud.availability_zones[(offset_number + self.facet_index) % self.cloud.availability_zones.size] rescue self.cloud.default_availability_zone                          
    end                                                                                                                                                                           
  end                                                                                                                                                                             
end
```

What I would like to have is an attribute of cloud like this

```
cloud(:ec2) do
     availability_zones  ('a'..'e').map { |z| "us-east-1#{z}" }                                                                                                                    
     zone_placement_strategy :hashed
    ...
end
```

Where zone_placement_strategy could be something like ':hashed' (like my monkeypatch) or ':together' or something else.

Is something like this on the roadmap, or are contributions welcome?

**Comment by temujin9** [comment]
We don't have anything on the road-map yet. I usually just do server(0).cloud(:ec2).availability_zones ["foo"] if I need to override it, which worked fine in v3.x and should translate to v4.x without difficulty.

Contributions are definitely welcome. Some pointers to get your pull requests accepted quickly:
1) Develop against the latest version (v4.x), not the 3.x branch you're currently using. I will be announcing EOL for 3.x fairly soon, and will only be doing bug-fix updates. See https://github.com/infochimps-labs/ironfan/wiki/Upgrading-to-v4 for how to switch over.
2) Don't change expectations for existing clusters (e.g. - make the default placement strategy :first, which does what it does currently).
3) Separation of concerns was a large motivation for the recent refactor. Try not to entangle parts of the code more than they already are. In particular, the DSL interpretation should be as static as possible.

Thanks!
