### ISSUE TITLE
ironfan-pantry: updated flume cookbook; prep required

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#157]
I updated the flume cookbook to allow install of the pre-release 0.9.5 snapshot: infochimps-labs/ironfan-pantry#5e797196 (flume updates) and infochimps-labs/opscode_cookbooks#3d1e41cb14b9 (supporting thrift changes). Cookbook version numbers were bumped so you can gate these changes into production.

There is now an install_from_git, which noisily builds a snapshot from a specified revision and lets you use it in place. I also took said snapshot and pushed it to github; `install_from_release` does the standard dl/un-tar/symlink dance. The roles now invoke `install_from_release`.

Before bumping, you must stop the flume processes:

``` sh
sudo service flume_agent_0 stop  # or maybe just sudo service flume_agent stop 
sudo service flume_agent_1 stop 
# you should see nothing running:
ps auxf | grep -C1 flume 
```

and move the old install aside:

``` sh
for foo in /usr/bin/flume /usr/lib/flume /usr/share/doc/flume* /var/run/flume /var/log/flume /etc/flume /root/.m2/repository/com/cloudera/*flume* ; do 
  echo "==== $foo" ; 
  dest="/away`dirname $foo`" ; 
  sudo mkdir -p $dest ; 
  sudo mv $foo $dest ; 
done 
```

Then run chef-client as normal.

@kornypoet and other end-users -- you'll need to update the `pom.xml` of flume deploys, etc., and see if infochimps flume plugins need any re-building. Also would like to be sure that the hadoop jar is the right hadoop jar. Also make sure your own `~/.m2` maven cache is clean.

**Comment by mrflip** [comment]
I undid my changes to the _roles_ -- the default `flume_master`, `flume_server`, etc now all invoke `install_from_package`. Tested on cerulean.

---

Also: In order to successfully use the install_from_git 0.9.5 branch, you must force the machine to use thrift 0.6.0; add the following to your clusters/ file (or modify the node attributes, or however you roll):

``` ruby
  cluster_role.override_attributes({
      :thrift         => { :version => '0.6.0', :release_url => 'http://archive.apache.org/dist/thrift/0.6.0/thrift-0.6.0.tar.gz', },
    })
```

I think that I can make install_from_package that doesn't care about the thrift version, but that will be a later update.

**Comment by temujin9** [comment]
## Caveat

Migrating to a newer version of flume may not be in our best interests on any platform, especially since we're considering switching to Stafka. If we choose to do this anywhere, it's going to be a touchy process, and will likely require hard-to-schedule client downtimes.
