### ISSUE TITLE
Remaining cookbook differences between master and version_2

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#16]
Most cookbooks are now the same between master (infochimps production versions) and version_2:

Here are the few remaining cookbooks that are different between the branches: 
- _hadoop_cluster,hbase,hive,cloudera_hue_. At some point in the future the versions in master will replace those in version_2. We will try to ensure stability for people using version_2 copies of those cookbooks.
- _big_package_: these are probably better in version_2 and I'll sort them out at some point.
- _elasticsearch_: one uses cluster discovery, one uses explicit seeds. You're working with these @temujin9, go with the one you think makes more sense.
- _redis_ -- see infochimps/cluster_chef#10 (cookbook standardization) for more
- _zookeeper_ -- see infochimps/cluster_chef#10 (cookbook standardization) for more
- _cookbooks/java, cookbooks/ubuntu_ -- the version_2 cookbook forces sun java, which is GOOD. openjdk is an infestation. I didn't pull this in to master, because it should be done thoughtfully.
## Changes made to each branch

You'll see a whole flurry of changes, I tried to only do things that wouldn't impact production.
### To version_2:
- new to the version_2 branch, pulled in wholesale from master: apache2, graphite, nagios, nodejs, ntp, python, statds
- fixes to cassandra and thrift from Mike Heffner.
- From the production versions in master, patches applied cleanly: flume, zookeeper, pig, jruby
### To master:
- backported fixes from the opscode-master for cookbooks/{aws,nfs,runit,thrift}
- nuked some bad symlinks
- fixes to the cassandra recipes
- fix to nfs recipe for NFS servers under ubuntu maverick
- new to the master branch, pulled in wholesale from version_2: Rstats, motd/...node_name
- a one-line nitpick in hbase.
## site-cookbooks vs cookbooks:

I pulled apache2, ntp, python into _site-cookbooks_ because that's where it was in master. I think many of these are unmolested copies from the opscode-cookbooks versions -- @temujin9, would you please relocate them into cookbooks and put only the overrides if any in site-cookbooks?

**Comment by howech** [comment]
I think that we are pretty much done with merging. If bugs come up because we were not done merging, they are now just bugs.
