### ISSUE TITLE
cluster role and facet role are not assigned to node

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#160]
Ironfan 4 doesn't assign cluster role and facet role to nodes

to reproduce, run `knife cluster show [cluster_name]`; near the end of the torrential information appears the runlist, lacking those roles. 

To work around this, simply add a `role [cluster]_cluster` at the end of the cluster def'n, and `role [cluster]_[facet]` at the end of each

**Comment by temujin9** [comment]
This is a regression; it worked right until very recently. Digging into it now.
