### ISSUE TITLE
Bootstrapping appears to disregard ec2_image_info :bootstrap_distro field

### ISSUE THREAD

**Issue by nickmarden** [infochimps-labs/ironfan#164]
Using ironfan 4.0.9 and chef-10.14.2, I'm getting an error at this line:

https://github.com/opscode/chef/blob/master/chef/lib/chef/knife/bootstrap.rb#L170

the #find_template method is returning nil, which results in this:

```
Can not find bootstrap definition for 
WARNING: No such file or directory
WARNING: ["/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-10.14.2/lib/chef/knife/bootstrap.rb:151:in `find_template'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-10.14.2/lib/chef/knife/bootstrap.rb:170:in `run'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/ironfan_knife_common.rb:147:in `run_bootstrap'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/cluster_launch.rb:114:in `perform_after_launch_tasks'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/cluster_launch.rb:86:in `block in run'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/ironfan.rb:32:in `block (2 levels) in parallel'"]
```

The relevant definition in my cluster file is:

```
cloud(:ec2) do
  availability_zones  ('a'..'c').map { |z| "us-west-2#{z}" }
  defaults
  permanent           false
  flavor              'm1.large'
  backing             'ebs'
  image_name          'gsfn-precise64'
  chef_client_script  'client.rb'
  mount_ephemerals
end
```

And the relevant section in my knife-org.rb is:

```
# Add your own AMIs to the hash below
Chef::Config[:ec2_image_info] ||= {}
ec2_image_info.merge!({
    %w[us-east-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-83db71ea', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
    %w[us-west-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-5965401c', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
    %w[us-west-2       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-ca038cfa', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
    %w[eu-west-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-ab9491df', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
    %w[ap-southeast-1  64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-acf6b0fe', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
    %w[ap-northeast-1  64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-c641f2c7', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
    %w[sa-east-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-5c03dd41', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
  })
Chef::Log.debug("Loaded #{__FILE__}, now have #{ec2_image_info.size} ec2 images")
```

This worked in Ironfan v3, but doesn't work now :-(

**Comment by mrflip** [comment]
working on this.

On Sat, Sep 22, 2012 at 10:19 AM, Nick Marden notifications@github.comwrote:

> Using ironfan 4.0.9 and chef-10.14.2, I'm getting an error at this line:
> 
> https://github.com/opscode/chef/blob/master/chef/lib/chef/knife/bootstrap.rb#L170
> 
> the #find_template method is returning nil, which results in this:
> 
> Can not find bootstrap definition for
> WARNING: No such file or directory
> WARNING: ["/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-10.14.2/lib/chef/knife/bootstrap.rb:151:in `find_template'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/chef-10.14.2/lib/chef/knife/bootstrap.rb:170:in`run'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/ironfan_knife_common.rb:147:in `run_bootstrap'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/cluster_launch.rb:114:in`perform_after_launch_tasks'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/chef/knife/cluster_launch.rb:86:in `block in run'", "/Users/nick/.rvm/gems/ruby-1.9.3-p194@ironfan-homebase/gems/ironfan-4.0.9/lib/ironfan.rb:32:in`block (2 levels) in parallel'"]
> 
> The relevant definition in my cluster file is:
> 
> cloud(:ec2) do
>   availability_zones  ('a'..'c').map { |z| "us-west-2#{z}" }
>   defaults
>   permanent           false
>   flavor              'm1.large'
>   backing             'ebs'
>   image_name          'gsfn-precise64'
>   chef_client_script  'client.rb'
>   mount_ephemerals
> end
> 
> And the relevant section in my knife-org.rb is:
> 
> # Add your own AMIs to the hash below
> 
> Chef::Config[:ec2_image_info] ||= {}
> ec2_image_info.merge!({
>     %w[us-east-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-83db71ea', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>     %w[us-west-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-5965401c', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>     %w[us-west-2       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-ca038cfa', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>     %w[eu-west-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-ab9491df', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>     %w[ap-southeast-1  64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-acf6b0fe', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>     %w[ap-northeast-1  64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-c641f2c7', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>     %w[sa-east-1       64-bit  ebs  gsfn-precise64] => { :image_id => 'ami-5c03dd41', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04-gsfn", },
>   })
> Chef::Log.debug("Loaded #{**FILE**}, now have #{ec2_image_info.size} ec2 images")
> 
> This worked in Ironfan v3, but doesn't work now :-(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/infochimps-labs/ironfan/issues/164.

## 

infochimps.com - discover data

**Comment by nickmarden** [comment]
Thanks, I'll test this now.
