### ISSUE TITLE
'terminated' and 'shutting-down' machines should not be bogus

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#165]
'terminated' and 'shutting-down' machines should not be bogus -- it's a perfectly expected circumstance. As a developer it's annoying -- leaving them marked as bogus means folks will get in the habit of adding `--force`, which is dangerous.

The previous version simply ignored them, which has always been fine. I suggest we go back to that behavior.

**Comment by temujin9** [comment]
Agreed: known (minor) issue, and if you can fix this without breaking other parts of the bogosity, please do.

**Comment by mrflip** [comment]
The main thing I need your guidance on is whether:
- a) 'terminated' and 'shutting-down' machines do not exist. They are rejected at the discovery phase and so nobody is ever aware of them.
- b) 'terminated' and 'shutting-down' machines don't exist, but you can ask about them: they are ignored during discovery unless the action requests their inclusion -- so `knife cluster show` would tell you about them, nothing else would.
- c)  'terminated' and 'shutting-down' machines exist, but various actions ignore them

I prefer (a) -- by the time a machine is in that state, there's nothing you can do about it, and in some number of minutes it will be gone anyway, and I don't believe in ghosts. It's also simple enough I can jump in and do it; (c) sounds like a lot of conditional logic in the wrong places. If you don't mind (a) I can push in a patch.

**Comment by nickmarden** [comment]
+1, and also I agree that (a) is the cleanest choice from a user's point of view. If people really care so much to look at their terminated or dying instances, there's always the AWS (or similar) interface.

**Comment by temujin9** [comment]
I would strongly prefer (c), even if we can't resurrect the corpses, which is why I didn't just do (a) myself. It does seem to require ugly conditional logic, which is why I'd held off.

**Comment by temujin9** [comment]
An acceptable compromise might be to add a flag (or interpret the existing -V flag) to `knife cluster show` to "display dead machines". That way, launch/etc. commands will ignore those machines, but I can still get my visibility without going all the way to the consoles.

**Comment by nickmarden** [comment]
I can be convinced of that as well, as long as I don't have to type --force (which I don't really ever want to type) in order to bring up a server that I recently terminated.

**Comment by mrflip** [comment]
okey doke:  `knife cluster show` will be the only one that brings up dead nodes, and only with verbosity >= 1.
