### ISSUE TITLE
Support Spot Instances

### ISSUE THREAD

**Issue by rberger** [infochimps-labs/ironfan#17]
Assuming my priorities don't get swapped out from under me, I'm going to be working on adding Spot Instance support to Fog and then to knife-ec2 plugin. Off hand it looks like most of the work is on the fog end. So that should be leveragable into the knife-cluster plugin.

So you can count me in to work on at least the Fog support starting within a week...

**Comment by temujin9** [comment]
Thank you for tackling this. We will be wanting this functionality ourselves, so do let us know if we can help.

**Comment by rberger** [comment]
I haven't been able to work on this, but have several conversations with geemus about how to do it got him to actually add it to fog. So fog now has the ability to request spot instances, describe requested spot instances, get spot instance price history and a few other very basic mechanisms. (https://github.com/geemus/fog/commit/b50b62d7bcb39370e36c599ffab54b66e422a120)

This creates the ability to request a spot instance, but that turns out to be only a trivial portion of being able to use spot instances with something like cluster_chef.

After  actually working with spot instances for a bit, its not clear to me if it really makes sense to have spot instances directly spun up by cluster_chef knife command. Spot instances are requested and then it takes an indeterminate amount of time to actually have them running, with the possibility of one or more requested instance not starting up at all or for a very long time. (though this has not yet happened to me).

Once they have started, they are pretty much exactly like normal instances except that they can not be "Stopped/Started", only rebooted or terminated. And of course they can be terminated by AWS if your spot bid price is exceeded by the capacity requirements of AWS. You can request multiple instances in one spot request, but they have to be all of the same time and same availability zone per request. If you want some instances of one type and others of another type, you have to make separate calls. Also if you want to have each instance have different user_data, EBS configuration, AMI etc, then you would have to make seperate request for each of those diffrent types. Each request can take a different amount of time to complete or one or more could fail and others succeed.

So I'm thinking that it may make more sense to have the ability to have a two phase start mechanism for spot instances.

Phase I could be a stand-alone knife command/utility that just starts up spot instances based on the cluster definition (actually I would create a non-clusther-chef specific tool that starts up spot instances based on arguments and/or generic config file and then have cluster-chef call it, since such a tool would be useful beyond cluster-chef)

Then one would have to decide how much you want to automate waiting for the spot instances to come up in order to do phase two. This becomes the potential nightmare of distributed asynchronicity. There needs to be a spot request per instance type, instance configuration and availability zone being used in a cluster. 

Its unknown when the requested instances will be available and if you are requesting multiple spot instances or multiple requests with different instance specfications, if they would all become available at the same time or not. So there would need to be various kinds of error handling. 

It could be done with some kind of master job forking subjobs to do the requests for each instance type / availability zone and then reporting back to the master. But that is a project in itself! 

One way or another the phase I tool would have to generate and track the results of each request, note the completion of the spot instances being instantiated and capture/record the instance ids. These may need to be ordered by instance type and availability zone if you are requesting against multiple types and/or zones . As part of capturing the info, it could lookup the public IP addresses of each instance as well to be used in Phase II.

To get started, it could take as long as it needs and generate an error if it actually fails. In any case it stores its results in machine readable form in some persistant store or queue mechanism (file, SDB, SQS, whatever) and its up to phase II to decide what to do. 

The completion of the Phase I spot requests (assuming no errors or timeouts) would trigger Phase II / Phase II would be listening on a queue or pub/sub or whatever for the completion of Phase I or a timeout. 

Or a Human manually starts the Phase II pointing at the results of Phase I after the Human makes sure everything is as need be for Phase II

Phase II could be or could call a version of the knife cluster-chef command that could take the list of the spot instances IP Addresses from Phase I, and do a a "bootstrap" instead of an "ec2 server create". Otherwise it would be the same as the current cluster_chef knife command

Having the ability to do the "bootstrap" in addition to the "ec2 server create" is a useful mechanism in other cases as well. (it can be used for non-ec2 environments or other cases where you have to redo the cluster command with existing instances. (the bootstrap mechanism might already be there in cluster-chef, I haven't checked)

**Comment by rberger** [comment]
Didn't mean to close it...

**Comment by emiddleton** [comment]
Don't know if this is useful to you.  This is my fork of knife-ec2 with spot instance support.

https://github.com/emiddleton/knife-ec2/

**Comment by temujin9** [comment]
Robert: I'm shuffling this around in priority, since we don't have a strong internal need. If you still need it, and put in a pull request code, I should be able to slot it in quickly (as I don't anticipate it introducing any breaking changes).

**Comment by rberger** [comment]
Yeah, it became a low priority for us as well. No big deal right now... THanks

**Comment by temujin9** [comment]
Looking at this further, I'm going to close it as a WONTFIX. The number of potential serious issues with getting Ironfan knife to work with a spot instance requests, combined with the low internal and external interest, makes it a non-starter. Feel free to reopen if you find your need for it spiking.
