### ISSUE TITLE
Virgin AMI Cluster boot

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#19]
There should be a mechanism to boot  a cluster from a virgin ubuntu AMI. This was supposed to happen as a part of the version_2 merge, but we decided to press forward with the merge without it.

**Comment by pcn** [comment]
Do I understand correctly that this means that cluster_chef will only work if launched from an AMI that is prepared per notes/burn_your_own_ami.textile?

**Comment by mrflip** [comment]
Using `knife cluster launch --bootstrap` is reliably launching clusters
