### ISSUE TITLE
Elastic IPs not handled correctly

### ISSUE THREAD

**Issue by temujin9** [infochimps-labs/ironfan#196]
They don't automatically attach, or factor into attempts to SSH into a host they're attached to.

**Comment by msaffitz** [comment]
I have a similar issue that a private IP address (assigned as part of a VPC) isn't being used for SSH attempts.  These instances don't have public IPs or hostnames that surface for connectivity.

**Comment by UncleTallest** [comment]
Are the two types of Elastic IP been treated as one? They seem to be different animals.

From the 'normal' Elastic IP Docs...

> **Important**
> If you're using Amazon Virtual Private Cloud: There's a separate pool of Elastic IP addresses to use with Amazon      VPC. Your Amazon EC2 Elastic IP addresses won't work with instances in a VPC, and your VPC Elastic IP addresses won't work with instances in EC2. The following sections describe how to work with EC2 addresses, which have different characteristics than VPC Elastic IP addresses...

Therein could lie the problem if we're expecting them to be similar.

**Comment by temujin9** [comment]
@schade - Deliverables are:
- Code in lib/ironfan/providers/ec2 to attach a specified Elastic IP (which is hand-generated) to a machine on launch.
- Code in lib/chef/knife/cluster_ssh.rb or other appropriate place to make `knife cluster ssh` work with the IP
- Testing done to ensure that this code works both in and out of VPC environments

**Comment by UncleTallest** [comment]
Part 1) attaching a specified Elastic IP in cluster definition now associates properly; however,
Part 2) connecting via ElasticIP via 'knife cluster ssh <facet-name>' is not yet complete.

Current code can be viewed at my fork https://github.com/schade/ironfan/commit/e6418e6c0337782f4764f621b8496bb2a065e93f. 
I will setup a pull request once the functionality of part 2 is complete.

Note: the changes to lib/ironfan/dsl/ec2.rb are merely removal of some of my testing code. All actual changes were done outside of the dsl.

No primates were harmed in the generation of this code...
