### ISSUE TITLE
Use alternatives to AWS user data

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#20]
There should be a way to bootstrap a node without having to rely on the AWS user data feature. This could be nice, for instance, in an environment that is not AWS EC2.

**Comment by mrflip** [comment]
fixed -- knife bootstrap writes the DNA into `/etc/chef/first_boot.json`

**Comment by mrflip** [comment]
fixed -- knife bootstrap writes the DNA into `/etc/chef/first_boot.json`
