### ISSUE TITLE
Cannot authorize Amazon ELB security groups

### ISSUE THREAD

**Issue by fractaloop** [infochimps-labs/ironfan#207]
Servers behind a load balancer need to authorize Amazon's ELB security group. When attempting to do this via the Ironfan DSL, a nil error is raised.

`cloud(:ec2).security_group(:mycluster).authorize_group("amazon-elb/amazon-elb-sg")`

**Comment by nickmarden** [comment]
I don't know if this helps, but the ELB code that I added a while back does this automatically. Therefore, you may consider adding an elastic_load_balancer stanza to your cluster file and letting it handle the authorization for you.

That said, this should probably Just Work, anyway.
