### ISSUE TITLE
Update tutorial and documentation from feedback

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#214]
Excellent feedback from @deepakl on the Install / docs ...

(cc @aseever @sya)

---
## Ubuntu Installation

Since the documentation is Ubuntu focussed, I created an Ubuntu Vagrant VM and started installing ironfan on it.
1. I was not sure which ruby version to use so I installed Ruby 1.8.7
   bundle install failed with the error:
   <pre>
   Gem::InstallError: chozo requires Ruby version >= 1.9.1
   </pre>

I reinstalled Ruby 1.9.1 and the bundle install went through
1. I tried running knife cluster list and got the following error:

<pre>
vagrant@precise64:~/homebase/knife/credentials$ knife cluster list
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- /var/lib/gems/1.9.1/gems/ironfan-4.5.1/lib/chef/knife/ironfan_knife_common (LoadError)
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from /var/lib/gems/1.9.1/gems/ironfan-4.5.1/lib/chef/knife/ironfan_script.rb:19:in `<top (required)>'
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
from /var/lib/gems/1.9.1/gems/ironfan-4.5.1/lib/chef/knife/cluster_stop.rb:19:in `<top (required)>'
</pre>

I did not try to investigate this since I wanted to follow the tutorial.
## OSX Installation

I then switched to installing ironfan on OSX. This went through fine and "knife cluster list" ran properly.
1. The documentation about launching clusters is out of date since all the clusters and cookbooks have been extracted to ironfan-pantry
2. I cloned ironfan-pantry as a sibling folder to homebase.
   I had to set $CHEF_HOMEBASE to the full path of this folder and rename example_clusters to clusters to get knife to recognize the existing cluster recipes.
3. The first time I ran knife cluster launch, I got these errors:
   
   <pre>
   a] ERROR: Connection refused connecting to localhost:4000 for /search/client, retry 1/5
   ERROR: Connection refused connecting to localhost:4000 for /search/node, retry 1/5
   ERROR: Connection refused connecting to localhost:4000 for /search/role, retry 1/5
   </pre>
   
   <pre>
   b] WARNING: InvalidKeyPair.Duplicate => Duplicate key found when creating keypair burninator
   ERROR: InvalidKeyPair.Duplicate => Duplicate key found when creating keypair burninator (Fog::Compute::AWS::Error)
   /Users/dlewis/.rvm/gems/ruby-1.9.3-p194@ironfan/gems/excon-0.16.10/lib/excon/connection.rb:292:in request_kernel'
   </pre>
   
   <pre>
   c] WARNING: Can't find image for ["us-east-1", "64-bit", "ebs", "ironfan-precise"]
   WARNING: Error running #<Ironfan::Broker::Computer(server=#<Ironfan::Dsl::Server(name="0", run_list_items=c{ role[chef_client], role[ssh], motd, role[burninator_cluster], role[burninator_village] }, clouds=c{ ec2 }, volumes=c{ root }, environment=:_default, cluster_role=#<Ironfan::Dsl::Role>, facet_role=#<Ironfan::Dsl::Role>, cluster_name="burninator", facet_name="village")>, resources=c{ client, node, keypair, security_group__ssh }, drives=c{ root, ephemeral0, ephemeral1, ephemeral2, ephemeral3 }, providers=c{ chef, iaas })>:
   WARNING: Failed validation: {"No AMI found"=>["burninator-village-0", "#<Ironfan::Dsl::Ec2(name=:ec2, default_cloud=false, availability_zones=[\"us-east-1a\"], backing=\"ebs\", bootstrap_distro=\"ubuntu10.04-ironfan\", chef_client_script=\"client.rb\", default_availability_zone=\"us-east-1a\", elastic_load_balancers=c{  }, flavor=\"c1.xlarge\", iam_server_certificates=c{  }, image_name=\"ironfan-precise\", mount_ephemerals={}, permanent=false, provider=Ironfan::Provider::Ec2, security_groups=c{ ssh, burninator, burninator-village })>"]}`
   </pre>
4. I fixed 3a by pointing chef_server_url to opscode. This is supposed to work by default.3b got resolved automatically during the second run.
5. The 'village' facet in burninator uses the 'ironfan-precise' image which does not exist. I changed this to 'precise' and this seemed to work.
6. The launch command failed again since 'us-east-1d' does not allow new instances to be provisioned and gave this error:
   
   <pre>
   WARNING: Unsupported => The requested Availability Zone is currently constrained and we are no longer accepting new customer requests for t1/m1/c1/m2 instance types. Please retry your request by not specifying an Availability Zone or choosing us-east-1c, us-east-1b, us-east-1a.
   </pre>
7. I switched to 'us-east-1a'. The next launch command created both the VMs but the chef-run failed on trogdor with the following error:

<pre>
Run list error:

ec2-50-16-144-135.compute-1.amazonaws.com  Adding system startup for /etc/init.d/chef-client-nonce ...
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc0.d/K20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc1.d/K20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc6.d/K20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc2.d/S20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc3.d/S20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc4.d/S20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com    /etc/rc5.d/S20chef-client-nonce -> ../init.d/chef-client-nonce
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:47+00:00] INFO: *** Chef 10.16.2 ***
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:49+00:00] INFO: HTTP Request Returned 404 Not Found: Cannot load role chef_client
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:49+00:00] ERROR: Role chef_client (included by 'top level') is in the runlist but does not exist. Skipping expand.
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:49+00:00] INFO: HTTP Request Returned 404 Not Found: Cannot load role ssh
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:49+00:00] ERROR: Role ssh (included by 'top level') is in the runlist but does not exist. Skipping expand.
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:49+00:00] INFO: HTTP Request Returned 404 Not Found: Cannot load role package_set
ec2-50-16-144-135.compute-1.amazonaws.com [2012-11-22T12:55:49+00:00] ERROR: Role package_set (included by 'top level') is in the runlist but does not exist. Skipping expand.
ec2-50-16-144-135.compute-1.amazonaws.com
ec2-50-16-144-135.compute-1.amazonaws.com ================================================================================
ec2-50-16-144-135.compute-1.amazonaws.com Error expanding the run_list:
ec2-50-16-144-135.compute-1.amazonaws.com ================================================================================
ec2-50-16-144-135.compute-1.amazonaws.com
ec2-50-16-144-135.compute-1.amazonaws.com Missing Role(s) in Run List:
ec2-50-16-144-135.compute-1.amazonaws.com
ec2-50-16-144-135.compute-1.amazonaws.com ----------------------------
ec2-50-16-144-135.compute-1.amazonaws.com * chef_client included by 'top level'
ec2-50-16-144-135.compute-1.amazonaws.com * ssh included by 'top level'
ec2-50-16-144-135.compute-1.amazonaws.com * package_set included by 'top level'
</pre>

1. Also, running "knife cluster kick burninator' fails with a similar error:
   
   <pre>
   Macintosh-4:ironfan-pantry dlewis$ knife cluster kick burninator
   Inventorying servers in burninator cluster, all facets, all servers
   burninator:       Loading chef
   burninator:       Loading ec2
   burninator:       Reconciling DSL and provider information
   +----------------------+-------+---------+-----------+------------+----------+------------+-------------+---------------+------------+
   | Name                 | Chef? | State   | Flavor    | AZ         | Env      | MachineID  | Public IP   | Private IP    | Created On |
   +----------------------+-------+---------+-----------+------------+----------+------------+-------------+---------------+------------+
   | burninator-trogdor-0 | yes   | running | c1.xlarge | us-east-1a | _default | i-4555393a | 23.23.25.62 | 10.159.24.190 | 2012-11-22 |
   +----------------------+-------+---------+-----------+------------+----------+------------+-------------+---------------+------------+
   ERROR: knife encountered an unexpected error
   This may be a bug in the 'cluster kick' knife command or plugin
   Please collect the output of this command with the `-VV` option before filing a bug report.
   Exception: NoMethodError: undefined method `each' for nil:NilClass
   </pre>
2. I don't where the chef_client, ssh and package_set roles are defined and I'd need help with this.

**Comment by temujin9** [comment]
Archiving.
