### ISSUE TITLE
Mongodb race condition starting server (use `notify_startable_services`)

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#217]
On a newly-installed machine, I had a race condition between the mongodb runit and its config file. This might be one of those things, or it might be that it's that way every new run. @brandonbell did you hit this ever?

If so, I blame the following warp in the chef-time continuum:
- `client` and `server` both need `config_files`, the same file. So we must not put the runit statement in there.
- `server` must precede `config_files` so that the config files knows what's up. This is the right place to put the `runit_service` statement. 
- However, the runit service definition will sometimes start the daemon immediately (as I've seen) -- meaning that the service may initiate before the config files are in place.

The solution is to use silverware's `announced_services` helper in the `config_files` cookbook. Refer to the existing-and-underused `notify_startable_services` helper (the DRY replacement for `notifies  :restart, "service[foo_server]", :delayed if startable?(node[:foo][:server])` in templates). The world could use a `kick_announced_services_for(:mongo)`, that does delayed-notify for each announced service in the mongo world, each with its own run state (I shouldn't have to hand it anything more than the service name).

(PS: those helpers have the faint smell of something I wrote before the conventions were nailed down solid: I'm not sure it fomulates service names right; and I shouldn't have to hand it the service names themselves. So if a person runs into problems and that person instead decides the solution is to <del>use</del> _steal code from_ silverware's `announced_services` helper in the `config_files` cookbook that'd be fine too.)

**Comment by brandonbell** [comment]
@mrflip - I dont recall experiencing the race condition, though I only spun up a fresh node once.  I'll move runit to the server recipe and add in notify_startable_services to config_files tomorrow.

**Comment by temujin9** [comment]
Appears to be fixed by https://github.com/infochimps-labs/ironfan-pantry/pull/12 and my subsequent commits. Closing.
