### ISSUE TITLE
new java recipe is missing things (alternatives, some symlinks)

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#226]
We're missing some things the old one did -- 
- doesn't ever actually make `node['java']['java_home']`
- calling update_alternatives
- some binary linkage

Worth running down the things the `java_ark` provider did. If you made the ark provider have multiple `action`s (instead of one mondo `action :install`) you could probably re-use most of it. The install_from recipe has an example of this.

**Comment by temujin9** [comment]
@mrflip - Does https://github.com/infochimps-labs/opscode_cookbooks/commit/9cc6ab6b9a707913c5d2ab160fad0520c0719f5a look any better to you?

**Comment by temujin9** [comment]
Fixed, closing.
