### ISSUE TITLE
Improvements to Hadoop fake topology

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#241]
Note: If you were using fake topology, the rack assignments have CHANGED. I don't think many were, but if you were please proceed with eyes open.

If you were not using fake topology this will not impact you at all.

Pull request at infochimps-labs/ironfan-pantry#16

---
- Assigns only two racks, 'lo' and 'hi'. That's all you should really be using with fake topology
- Better explanation of caveats and motivation
- increased topology.script.number.args so script is used fewer times

When you first add fake topology, you must force Hadoop to migrate blocks to the new policy. This is best done by annealing the replication factor up, then down -- see hadoop_cluster/recipes/fake_topology.rb for instructions.

**Comment by temujin9** [comment]
Nobody running clusters is actively using it, save maybe @dieterichlawson (who should consider this his warning). Merging in the pull and closing this.
