### ISSUE TITLE
git submodule update fails with error: fatal: reference is not a tree: 6e7decb59e256adcb0b48f064bb66cde066af0d8

### ISSUE THREAD

**Issue by initcron** [infochimps-labs/ironfan#245]
$ git submodule update
fatal: reference is not a tree: 6e7decb59e256adcb0b48f064bb66cde066af0d8
Unable to checkout '6e7decb59e256adcb0b48f064bb66cde066af0d8' in submodule path 'knife/example-credentials'

**Comment by temujin9** [comment]
Dammit. What repo are you on?

**Comment by temujin9** [comment]
Ah, sorry: you're obviously in ironfan-homebase. Checking now.

**Comment by temujin9** [comment]
That was my bad: I fiddled with some internal stuff, and apparently managed to connect my submodules to the wrong repo for long enough to push the wrong SHA. Sorry; it should be fixed now, if you merge from upstream.
