### ISSUE TITLE
knife cluster [kill & launch] give missing method errors on 'name'

### ISSUE THREAD

**Issue by LeeGraber** [infochimps-labs/ironfan#251]
I am using ironfan 4.7.7 and chef 10.16.4. When I run bundle exec knife cluster kill <cluster> I get:
WARNING: Error running Ironfan::Provider::ChefServer::Client[adaptee,bogus,key_filename]:
WARNING: undefined method `name' for #<Hash:0x007feb67a5b770>
ERROR: undefined method`name' for #Hash:0x007feb67a5b770 (NoMethodError)
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider/chef/client.rb:6:in `name'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider.rb:109:in`remember'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider.rb:117:in `register'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider/chef/client.rb:51:in`block in load!'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.16.4/lib/chef/search/query.rb:44:in `call'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.16.4/lib/chef/search/query.rb:44:in`block in search'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.16.4/lib/chef/search/query.rb:44:in `each'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/chef-10.16.4/lib/chef/search/query.rb:44:in`search'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider/chef.rb:24:in `search'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider/chef/client.rb:49:in`load!'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan/provider.rb:36:in `block in load'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan.rb:35:in`block (3 levels) in parallel'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan.rb:134:in `safely'
/Users/leegraber/.rvm/gems/ruby-1.9.2-p290/gems/ironfan-4.7.7/lib/ironfan.rb:34:in`block (2 levels) in parallel'
...
In 4.7.7 it actually continues and completes most of the time but I would like the errors to go away. I have tried playing around with a wide variety of combinations of chef and ironfan but each one seems to be having issues. On earlier versions of ironfan I got a similar error except the method was "cluster_name" and I was not given a stack and it failed the operation. On earlier versions of chef knife stopped working. This was all working at one point but I am trying to move forward versions of these libs and now cannot seem to get back to a stable state. Please advise

**Comment by temujin9** [comment]
Update your homebase to use the latest Gemfile and Gemfile.lock. The latest update to json once again killed things; we're now pinning it to 1.5.4, and distributing the Gemfile.lock to help people stay in sync.

**Comment by temujin9** [comment]
(By "update your homebase" I mean "pull from the ironfan-homebase, and run bundle install".)

**Comment by LeeGraber** [comment]
Thanks. That seems to have fixed that issue :)
