### ISSUE TITLE
Elasticsearch Improvements

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#261]
See infochimps-labs/ironfan-pantry#28
- !!IMPORTANT!! The elasticsearch data directory was being set by the transgressive attribute 'data_root'; worse, the scratch space was locked to being a subdirectory of that. Now actually uses the volume_dirs. This is necessary for switching to the 'local' gateway mode.
        - node[:elasticsearch][:data_dir], set by the :elasticsearch_data tag on a volume, defines where data goes ('ES_DATA_DIR');
        - node[:elasticsearch][:scratch_dir], set by the :elasticsearch_scratch tag on a volume, now specifies the scratch dir ('ES_WORK_DIR')
        - if you were using :data_root, it will complain and make you change it. The work_dir may change, but that shouldn't matter to you.
- Hosts in discovery are sorted so their order in the list doesn't dance
- Added the 'head' and 'bigdesk' dashboard plugins. Neato!
- Changed the plugins definition to use a hash, not a string. It will still accept your string, but it will holler. I might make it just break instead, so update your overrides.
- Added an 'overall' log setting -- use it to set the baseline log4j log level
- if you are a data node, node.name is set to the machine name and 'max_local_storage_nodes' is set to one.
- set the minimum_master_nodes value to 1 + (number of seeds / 2) to prevent split-brain in clusters of size > 2

**Comment by temujin9** [comment]
Sweet.

Todo (for me):
- Push up to testmonkey-homebase
- Validate or update current upgrade strategy:
  - (Prep: make a cluster with the current `:staging` version)
  - (Prep: simulate a strong load against the servers?)
  - Add a node
  - Reconverge other nodes
  - Wait for green on /cluster/_health
  - Recapitulate & wait for green each old server, in turn
  - Kill extra server
- Or just an update strategy:
  - (Prep: make a cluster with the current `:staging` version)
  - (Prep: simulate a strong load against the servers?)
  - Switch cluster to newest code (`:development` in test, `:staging` in production)
  - Reconverge & wait for green on each server, in turn
- Once those are done: push code into master (for final CI sanity checks)
- Work with lead developers to deploy in other homebases

**Comment by mrflip** [comment]
Note that @mccuistion and I have had it on testmonkey homebase and have
been beating on it for several days; we finished the second rolling recap
on it yesterday (first was ephemeral raid => EBS raid, then EBS raid =>
just plain EBS).

You can soft-decommission nodes using the c.r.allocation.include call:

```
curl -XPUT
```

http://projectes-elasticsearch-5.test.chimpy.us:9200/pageviews,articles,pagelinks/_settings

```
    -d '{ "index.routing.allocation.include.ironfan_name" :
```

"projectes-elasticsearch-0,projectes-elasticsearch-1,projectes-elasticsearch-2,projectes-elasticsearch-5"
}'

Would knock out nodes 3 & 4 leaing only 0,1,2 and 5. This would let you
proceed much faster, and stay green the whole time.

For reference, there is apparently another way to migrate from an S3
gateway to a local gateway:
- start the cluster (nodes as gateway nodes)
- put it in read-only mode
- bring up _new servers on the same machines_ as local-gateway nodes and
  have them join the same cluster
- bring down all the machines
- start the cluster with local gateway

This doesn't help us because we need to have EBS-backed volumes on the
machines, so we might as well just bring up nodes.

**Comment by temujin9** [comment]
Ah, thank you.

I'll run through with Rachael what y'all did, and probably do a roll just to be sure before I start recommending production pushes, but I probably won't have as much to do.

[Shard Allocation Filtering](http://www.elasticsearch.org/guide/reference/modules/cluster.html) will probably improve the decommissioning process, yes.

We should really get people using the `:production` environment before we deploy this, as it is a breaking (i.e. manual intervention required) change.

**Comment by mrflip** [comment]
Please note that local gateway mode is _not_ required for these changes --
the only crucial change is to the data_root handling.

I can restore the logic to respect the old node attribute if we don't like
to wait until the pull request can come in.

flip

**Comment by temujin9** [comment]
I've merged. To clarify: the code looks like it was put back to the original S3 gateway mode. Let me know when you're wanting to change that, because it seems like a bit more of an ops-intensive process.
