### ISSUE TITLE
Wiki page unclear, image definition question

### ISSUE THREAD

**Issue by radekg** [infochimps-labs/ironfan#267]
I was following this page https://github.com/infochimps-labs/ironfan/wiki/INSTALL to install everything and I've noticed a couple of issues with the description:

```
Put the Chef user key in knife/credentials/{username}.pem at.
```

I had to use `validation.pem`, not `client.pem` as suggested by the above.
Another issue, which is more a thing not being mentioned, is the images. Could you please describe how to configure images in the `knife-org.rb` file as that isn't clear either?

Last question, related to images. I have placed my instances in us-west-2a AZ but the image definition had to be:

```
%w[us-west-2  64-bit  ebs  portico-default ] => { :image_id => 'ami-4ac9437a', :ssh_user => 'ubuntu', :bootstrap_distro => "ubuntu12.04", }
```

Even though my cluster definition says:

```
availability_zones ['us-west-2a']
```

Is this a known issue?

**Comment by temujin9** [comment]
`validation.pem` is a site-wide key that anyone in your organization can regenerate, and sharing it is bad security practice. The instructions show how to get your client.pem from your Opscode password management page; admittedly that's not the most intuitive place to look for it, but that's where they put it.

The image configuration is best documented [in the example-credentials/knife-org.rb comments](https://github.com/infochimps-labs/example-credentials/blob/master/knife-org.rb#L58). Do those notes help clarify the process any for you?

The images are region-wide (e.g. `us-west-2`), and availability zones are subsets of regions (e.g. `us-west-2a`).

**Comment by radekg** [comment]
No, it did not work for me with client.pem generated on self hosted chef server. I had to use validation.pem.

**Comment by temujin9** [comment]
Ah, that's the issue: self-hosted chef has a different security setup. You _can_ use validator, but it's not something we support. For self-hosted chef, you should make a client with the same name as the user, give it sufficient permissions, and download it's PEM.

I've updated the documentation to note that difference. I'm not going to go in depth there, largely because I want to keep the install documentation from sprouting lots of edge-cases (of which there are many).

**Comment by radekg** [comment]
Thanks, I've noticed that the documentation is really sparse on some topics.
