### ISSUE TITLE
Missing dependency in step 1 of Debian/Ubuntu Install Instructions

### ISSUE THREAD

**Issue by UncleTallest** [infochimps-labs/ironfan#270]
We need to add `zlib1g-dev` to step one of the Debian/Ubuntu install instructions so gem can find it when installing gems. Otherwise, as soon as you try to use this command:

``` ruby
gem install bundler
```

it will die a horrible death complaining it isn't there; also if you've made the mistake I did and had already used:

``` ruby
rbenv install 1.9.3-p392
```

you'll need to do the folowing:

``` ruby
rbenv uninstall 1.9.3-p392
sudo apt-get install zlib1g-dev
rbenv install 1.9.3-p392
```

to be able to use it. From there you should be able to use the installation as written.

**Comment by UncleTallest** [comment]
On another note, since the default install method is now via rbenv the line about using `rbenv rehash` after running `gem install bundler` should probably be moved up into the code block where it belongs.

**Comment by temujin9** [comment]
Fixed the missing dependency. The `rbenv rehash` needs to happen after the gem is installed, which moving it would not easily accomplish.
