### ISSUE TITLE
Cookbooks and cluster configuration should be cloud agnostic

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#28]
The recipes have EC2 intertwingled in various places. 

We're hoping some folks in the community can help abstract the cloud dependencies, so that all the recipes work on EC2, Rackspace, other cloud providers and non-cloud machines.

Pull requests are welcome. The best solution will leave the recipes modular and not require conditional logic.

The cluster_chef library needs integration:
- `/lib/cluster_chef/compute.rb` -- has only ec2 cloud integration so far
- `lib/cluster_chef/cloud.rb`: The `cloud` statement should allow
  - with no argument, describes physical attributes of the machine generically, using the terminology of Fog.
  - with a provider, describes provider-specific configuration, and settings that apply only when on that provider.
  
  ``` ruby
  cloud{}             # ...machine's physical configuration) 
  cloud(:ec2){}       # ...physical configuration and attribute overrides when on ec2)
  cloud(:rackspace){} # ...physical configuration and attribute overrides when on rackspace)
  cloud(:local){}     # ...physical configuration and attribute overrides when on raw hardware)
  ```

Several cookbooks require abstraction:
- In several places, we access the `@node[:ec2][:public_hostname]` explicitly. This should be abstracted -- perhaps through a chef library?
- `site-cookbooks/motd`: report parameters regardless of cloud.
- `site-cookbooks/big_package`: separate out aws-specific packages.
- `site-cookbooks/elasticsearch/recipes/http.rb`: abstract the load_balancer logic.
- `site-cookbooks/hadoop_cluster`:
  - much of the configuration takes place in `recipes/ec2_conf.rb`.
  - The machine parameters tuning in attributes/hadoop_cluster.rb is very intertwingled
  - `templates/webfront_index.html.erb` has a lot of references to ec2 parameters
  - `roles/hadoop_s3_keys.rb` should be cloud agnostic

Probably safe, but could benefit from a _clean_ way to inject cloud-specific template content
- `site-cookbooks/cassandra`
- `site-cookbooks/elasticsearch`
- `site-cookbooks/flume/templates/default/flume-site.xml.erb`
- `site-cookbooks/hadoop_cluster/templates/default/core-site.xml.erb`

**Comment by mrflip** [comment]
Major progress on this in v3 --
- all the cookbooks are clean to work on Vagrant/Virtualbox AND ec2 cloud, so you won't have to do any cleanup and will have a base to compare against.
- The cluster_chef tools (`lib/*`) are not perfectly clean yet, but are getting close -- see #75 
- As soon as anyone steps up to make this work with an alternate cloud provide we're glad to provide matching effort...

**Comment by jessehu** [comment]
Hi mrflip,  it's great to see cluster_chef extends the support to various cloud provider.  Is there any sample code and guide to use Vagrant/Virtualbox?  If i want to extents cluster_chef to support vSphere, could you give some hints on where to add code ?   Thanks!

**Comment by mrflip** [comment]
@jessehu we are in fact working on vagrant support, and would love any help you can lend -- check out https://github.com/infochimps-labs/cluster_chef-homebase/tree/master/vagrants

Be warned though that this is in current development, the code itself will be much more reliable source of what to do than the documentation.

There's these pieces:
1. getting all the cookbooks to work fine in a vagrant environment. This has basically been accomplished.
2. getting a local vagrant setup on your machine, tailored for chef development. [These directions](https://github.com/infochimps-labs/cluster_chef-homebase/tree/master/vagrants) are mostly accurate but will for sure break in a couple places.
3. Enable cluster_chef to translate a cluster file to a Vagrantfile just as it currently targets fog 
4. Enable `knife cluster [whatever]` commands target vagrant -- for instance, `knife cluster launch` calls into the vagrant code, ultimately invoking the same methods `vagrant up` would.

I'm working on no.2 next; no.3 will probably involve some minor forays into the cluster_chef lib. Would absolutely love any contributions on no.4 (or no.3) you'd care to lend.

**Comment by jessehu** [comment]
@mrflip thanks for your feedback :)  The branch you pointed out doesn't have the folder lib/cluster_chef (https://github.com/infochimps-labs/cluster_chef/tree/master/lib/cluster_chef/knife) , seems it's not a workable cluster_chef code.  I'm really interested at getting the your new code with hard-coded ec2 related stuff removed.   Currently I just hard-coded vsphere stuff instead of ec2 to make cluster_chef (version 0.1.10) running on vsphere.

**Comment by mrflip** [comment]
What I pointed to is the cluster_chef-homebase -- this is a descendent of the opscode/chef/chef-repo, but fleshed out to be a full setup. There are detailed instructions for getting it to work. 

It uses the cluster_chef knife tools, whcih are best installed using `gem install cluster_chef` (or better yet `bundle install` from the base dir of the cluster_chef-homebase checkout.

**Comment by jessehu** [comment]
@mrflip thanks, i will have a try, and where can I get the cleaned cookbooks, as you said :  all the cookbooks are clean to work on Vagrant/Virtualbox AND ec2 cloud, so you won't have to do any cleanup and will have a base to compare against.  I want to try whether the new cookbooks works for vsphere cloud based on my forked cluster_chef code.

**Comment by jessehu** [comment]
Hello @mrflip,  could you let me know which fork of cluster_chef is the one that Infochimps are working on ?  I found there are many forks of it, but don't know which is the latest to use.   

Thanks!

**Comment by janewilkin** [comment]
How are things looking now that OpenStack support is released?

**Comment by temujin9** [comment]
The v4.x branch has much better separation of concerns between cloud provider and core Ironfan: I'm going to close this as finished. There are at least a few key places, labelled with CODE SMELL warnings, where separation could be improved; tracking of any specifics that become critical to end-users can be done in new issues.

@garrettwilkin Openstack is on the list, but not at the top of it. If you've got a deep interest, let me know and I'll put you on the list of folks to show how to build provider plugins.

**Comment by shredder12** [comment]
Hi @temujin9, is anyone from dev. team working on adding OpenStack support? I'm interested and would be happy to contribute. If it hasn't started, I'd be grateful if you could provide me some guidance on building provider plugins.

**Comment by UncleTallest** [comment]
We're currently discussing this on the ironfan-users group located here => https://groups.google.com/a/infochimps.com/forum/?fromgroups=#!topic/ironfan-users/fXQ3nalT59M%5B1-25-false%5D

**Comment by temujin9** [comment]
@shredder12 - We'd love to get your contribution. Providers aren't well documented yet, but I'm putting that on my agenda now ( #249 ), since several people have expressed interest in building them. As @schade  says, the email group is probably your best bet in the mean time.
