### ISSUE TITLE
Remove customer names from ironfan-homebase / example_clusters

### ISSUE THREAD

**Issue by arrawatia** [infochimps-labs/ironfan#287]
We should remove customer names from these examples.

hb.rb - "# Copied from neptune cluster (spongecell-homebase)"
kafka.rb - "# Copied from discoveryone wcg cluster"
tri.rb - "# Copied from niobe cluster (whaleshark-homebase)" and "      dds: { deploy_pack: 'git@github.com:infochimps/whaleshark-logdelivery.git' }"

**Comment by sya** [comment]
Thank you for finding. I have pushed changes.
