### ISSUE TITLE
Cannot bootstrap example clusters

### ISSUE THREAD

**Issue by mairbek** [infochimps-labs/ironfan#291]
I'm trying to bootstrap some example clusters, for example `bundle exec knife cluster launch el_ridiculoso-gordo --bootstrap`, I get following error:

> ec2-67-202-27-190.compute-1.amazonaws.com 0 upgraded, 0 newly installed, 0 to remove  and 0 not upgraded.
> ec2-67-202-27-190.compute-1.amazonaws.com ln: 
> ec2-67-202-27-190.compute-1.amazonaws.com failed to create symbolic link `/usr/bin/ruby'
> ec2-67-202-27-190.compute-1.amazonaws.com : File exists
> ec2-67-202-27-190.compute-1.amazonaws.com 
> ec2-67-202-27-190.compute-1.amazonaws.com Chef bootstrap failed!

It seems like it fails on line 52 of `ironfan/lib/chef/knife/bootstrap/ubuntu12.04-ironfan.erb` file.

**Comment by temujin9** [comment]
Most clusters aren't intended to be bootstrapped; they come aimed at an AMI which has already gone through the process. The exception to this is the `burninator` cluster, which is used for building the AMI. For what you're doing, launch without bootstrap should be sufficient.
