### ISSUE TITLE
knife cluster kick does not seem to be working

### ISSUE THREAD

**Issue by timgasper** [infochimps-labs/ironfan#299]
I'm pretty new to Ironfan, so pardon my naivety if this is a PEBKAC issue, but the kick command doesn't seem to want to work.

$ knife cluster kick hdp-master
Inventorying servers in hdp cluster, master facet, all servers
  hdp:              Loading chef
  hdp:              Loading ec2
  hdp:              Reconciling DSL and provider information
  +--------------+-------+---------+----------+------------+-------------+------------+--------------+---------------+------------+
  | Name         | Chef? | State   | Flavor   | AZ         | Env         | MachineID  | Public IP    | Private IP    | Created On |
  +--------------+-------+---------+----------+------------+-------------+------------+--------------+---------------+------------+
  | hdp-master-0 | yes   | running | m1.small | us-east-1d | development | i-da3f44b2 | XX.XXX.XX.XX | XX.XXX.XX.XXX | 2013-06-12 |
  +--------------+-------+---------+----------+------------+-------------+------------+--------------+---------------+------------+
ERROR: knife encountered an unexpected error
This may be a bug in the 'cluster kick' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `each' for nil:NilClass

**Comment by temujin9** [comment]
Kick involves SSHing into the machine, and you may not be trying with the right username. See if `knife ssh` results in a similar error. If so, try `-x ubuntu -i knife/credentials/ec2_keys/hdp.pem`, to log in with the system credentials. Reopen this if it's neither of those, with a full dump (including the result of the same command with `-VV` added).
