### ISSUE TITLE
Proposal: add identification information to aws tags

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#30]
Currently, ClusterChef discovers cluster/facet membership by looking at aws security groups. If we were to add instance tags, we could unequivocabably identify a cluster node just from the aws data. This could become the primary method for cluster discovery with internal chef data acting as a backup if the tagging information is missing. Also, cluster chef could ensure that the tags and internal chef data match up on a "cluster show". 

This would make it so that cluster chef would not have to wait for chef-client to run to be able to reconcile cluster nodes.

**Comment by temujin9** [comment]
+1

**Comment by howech** [comment]
Done. Tags (cluster, facet, index) are now created as a part of cluster launch. If these tags are present, they are used in cluster discovery.
