### ISSUE TITLE
Cookbook 'dashpot' not found in any of the default locations

### ISSUE THREAD

**Issue by mcsimm** [infochimps-labs/ironfan#301]
When I do 'berks install' in the ironfan-homebase repository, it give me "Cookbook 'dashpot' not found in any of the default locations" error.

Probably the reason is the dependency declared in "ironfan-pantry/cookbooks/cube/metadata.rb" - 
"
%w[silverware git nodejs dashpot].each do |cb|
    depends cb
  end
"

Is dashpot missing or I am doing something wrong?

**Comment by temujin9** [comment]
Ah, bother. I recently moved a bunch of cookbooks to open source from the private cookbooks that Infochimps keeps to support the full Platform, and I didn't do a thorough enough job checking dependencies. I've pulled cube until it can be fully open sourced. Thanks for the catch.
