### ISSUE TITLE
Proposal: move cluster definition data into a databag

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#31]
This would make cluster definitions behave more like native chef roles.

Currently, the cluster representation gets built from the cluster file when you run "knife cluster command". Unfortunately, in a multi-user environment, this leaves it susceptible to the users making sure that they are in sync with the cluster definition. 

This proposal would be to add a "knife cluster from file" command which would take the cluster definition and compile it into a static json representation and upload it into a chef databag. At the same time, commands like "knife cluster kill", "knife cluster launch", etc would pull the cluster definition down from the databag instead of trying to load it from the ruby files.

This proposal would help to ease multi-user syncronization issues.

This proposal would eliminate the ugly ruby lib manipulation code that gets cluster definitions to load, easing the way forward for a cluster_chef gem installation.

**Comment by mrflip** [comment]
-1 unless this is causing major headaches -- it's good to have truth unambiguously stem from one place (the files in the git repo) and to have that be diffable and inspectable. If it's useful to _mirror_ that truth up to a databag for other nodes to draw on, that's great -- but it should be hard for the databag copy to get out of sync with the repo truth.
I'm not dead-set against it -- just don't see enough demonstrated pain or terror to warrant it
