### ISSUE TITLE
Fallback to {cluster_chef_path}/clusters

### ISSUE THREAD

**Issue by mheffner** [infochimps-labs/ironfan#33]
Right now when creating a custom cluster definition and placing that definition in a custom `cluster_path`, there's no way to do:

```
use :defaults
```

without also copying/symlinking the default cluster definition into the custom `cluster_path`. It would be nice to be able to have a custom cluster definition in a custom directory while also being able to reference the default cluster definitions shipped with cluster_chef.

How about a fallback mechanism that will check cluster_path -> cluster_chef_path/clusters in order?

**Comment by howech** [comment]
I am going to change the mechanism for loading cluster specs shortly -
it will allow you to specify in your knife.rb file several directories
that contain cluster definitions. This will unlink the cluster
definitions from the location of the cluster_chef library.

**Comment by howech** [comment]
Chef::Config[:cluster_path] is now interpreted as an array of directories that
are expected to contain cluster definitions. ClusterChef.load_cookbook will now
traverse the array in order, looking for the requested cluster definition in
each directory, and attempts to load the first one that it finds.

By default, the cluster_path is set to the directory that cluster chef used to look
for cluster definitions.

To point cluster chef at a new set of directories, add something like the following
to your knife.rb file:

``` ruby

cluster_path ['cluster_chef/clusters',
              'infochimps_chef/clusters',
             ].map { |path| File.join("/home/chris/ics/sysadmin", path) }

```

This behavior is very similar to the way "cookbook_path" works...
