### ISSUE TITLE
knife cluster {stop|start} cluster [facet]

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#36]
a user should be able to

``` sh
  knife cluster {stop|start} cluster [facet]
```

**Comment by howech** [comment]
I added commands "knife cluster stop" and a "knife cluster start" - at the moment they are pretty basic. "stop" will ask for confirmation. Neither of them tells you exactly what it is doing.   Use "knife cluster show" before and after your stop/start command to get a feel for what it will do/ has done.
