### ISSUE TITLE
Clusters, facets, and servers should implement display code in compute.rb

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#37]
Currently, the display code is implemented in the cluster_xxxx.rb commands. This should be abstracted up to the compute.rb layer.

**Comment by mrflip** [comment]
+1

Between this and infochimps/cluster_chef#38 should we make a mixin for all the plugins use -- calls on methods in compute.rb etc but handles the concerns of the commandline tools?

**Comment by howech** [comment]
You can now call "display" on ComputeBuilder objects and it will draw you a table. If you dont like the table it draws, you can customize it by passing an array of column headers and a code block to calculate values from servers. See code for details.
