### ISSUE TITLE
Deprecate role/recipe inclusion in cluster definitions

### ISSUE THREAD

**Issue by temujin9** [infochimps-labs/ironfan#40]
Roles and recipes included directly from cluster definitions are written into node metadata on opscode, and must be edited manually with knife to remove. This is the core of the "hadoop_cluster::system_internals" bug we keep encountering: although it was updated in all roles, it was also present in some node meta-data.

Both the cluster and it's individual facets can establish roles and recipes associated with a collection of systems, in a way that allows for more consistent editing, updating, and revision tracking. There's no benefit to duplicating that capability inside of cluster definitions, and several drawbacks. I'd recommend we stop using that capability, and deprecate it in cluster_chef, ASAP.

**Comment by mrflip** [comment]
Going from these general principles:
- Chef server is _never_ the repository of truth -- it only mirrors the truth.
  - a file is tangible and immediate to access
- Specifically, we want truth to live in the git repo, and be enforced by the chef server. There is no truth but git, and chef is its messenger.
  - this means that everything is versioned, documented and exchangeable.
  - we acheive this goal except in one important case, the run list (this is the source of the bug you're seeing)
- All major systems, services and significant modifications to the machines in a cluster should be in front of me on the page when I look at its `clusters` file.  I don't want to have to bounce around nine different files to find out which thing installed a redis:server.
- ...you don't want to get too detailed though -- roles exist for a reason, and if cluster files start getting unruly.
- It's nice when machines are in full control of their destiny.
  - initial setup (elastic IP, attaching a drive) is often best enforced externally
  - but machines should be ablt independently assert things like load balancer registration that that might change at any point in the lifetime.
- It's even nicer, though, to have full idempotency from the command line: I can at any time push truth from the git repo to the chef server and know that it will take hold.

First, about the stale recipe: the initial minimal DNA for a node is _not_ in the machine's user-data, but in `/etc/chef/client-config.json` file

On startup:
- knife reads the cluster definition
- it puts a minimal amount of DNA into the node's user-data hash, passed along via the EC2 command.
- when the node starts up, it does the following:
  - makes an empy config hash.
  - If the node's `user-data` is valid JSON, merge it into the config hash.
  - if there is a file called chef-config.json, merge its contents into the config hash
  - if there is a file called client-config.json, merge it into the `:attributes` sub-hash of the config.
- The outside part of the config (not the attributes field) has the info required for the node to discover its purpose and connect to the chef server (server url, validation_key, etc)
- If the `client-config.json` file is missing, it is created using the attributes subhash. Basically, this means that you can use that file to override anything set in the (immutable) user-data. Not the best thing, but it does work.
- The elements in the attributes field are passed to `json_attribs` to become chef node attributes, and **win out over anything in the git repo**.  This is bad.

## Proposal

Using a hadoop cluster called 'gibbon' (with namenode, jobtracker and workers) as an example:

### in `clusters/gibbon.rb`:
- physical configuration:
  - machine size, number of instances per facet, etc
  - external assets (elastic IP, ebs volumes)
- high-level assembly of roles and systems:
  - roles hadoop_namenode, nfs_client, flume_client, etc.
- important modifications:
  - cluster_chef::system_internals, mounts ebs volumes, etc
- override attributes:
  - heap size, rvm versions, etc.

### implement a a `knife cluster sync` command
- pushes override attributes to the chef server
- pushes the runlist to the chef server
  - knife cluster bootstrap and knife cluster launch both invoke knife cluster sync.

### in `roles/`
- High-level roles that assemble recipes.
- Cluster and facet roles (`roles/gibbon_cluster.rb`, `roles/gibbon_namenode.rb`, etc) go away; override attributes go into the cluster.
  - currently, those files are typically empty and are badly cluttering the roles/ directory.
  - the cluster and facet override attributes should be together, not scattered in different files.
- roles shouldn't assemble systems. The contents of the `infochimps_chef/roles/plato_truth.rb` file belong in a _facet_.

### in the machine's user-data:
- the user-data should only have the minimal information required to join the chef server.
  - remove the run_list and aws fields
  - keep the cluster/facet/index identification
  - unfortunately, also have to keep the validation info
- Passing information in through the user-data is essential to be able to launch 30+ node clusters reliably. External surgery is problematic.

**Comment by mrflip** [comment]
Proposed fix for this is that we _only_ use the outer role / recipe keywords to fix the runlist.  Right now many cluster definitions have these duplicated.  

We need to 
- add the code that does the runlist injection for us
- make knife create the node if it doesn't exist.

A few reasons why you must/should have the roles under control of cluster_chef:
- security groups implied by roles (`nfs_client` etc)
- separation of cluster/facet runlist contributions
- It's a cleaner expression

**Comment by mrflip** [comment]
Closing since the support work is done; final cleanup of role/cluster/recipe separation will be done as part of the README-checklist.md process.
