### ISSUE TITLE
cluster_chef discovery fails with fog version 0.90

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#42]
It looks like the way to access security groups through fog has changed. This caused the discovery mechanism to fail to find any appropriate servers.

Searching by security group is probably obsolete. We can probably just go with tags.

Alternatively, we could figure how to do the same thing we were doing with fog-0.90 and make it work like before.

**Comment by mrflip** [comment]
Does fog still set up security groups?

Tags seem to work great, and (if there's an alternate way to discover membership) the knife sync command will go back and apply tags.

So as long as fog _applies_ security groups at launch, I don't mind losing them as a discovery mechanism.

**Comment by mheffner** [comment]
+1 for using tags instead of security groups.

**Comment by howech** [comment]
I think that there might be a bug in fog 0.90.  The "groups" container
is still there on the server object, but it is not getting populated for
any of our servers.

I still like the idea of discovery based on tags instead of security
groups, even if the bug were not there, so I put it in this morning.

--Chris

**Comment by howech** [comment]
I have reported a bug in fog about its failure to properly discover security groups for running instances: https://github.com/geemus/fog/issues/425

I tested to make sure that instances launched with fog 0.9.0 are granted membership to the correct security groups - they are.
