### ISSUE TITLE
Cluster ssh fails when there is no chef_node present

### ISSUE THREAD

**Issue by howech** [infochimps-labs/ironfan#43]
Currently, cluster ssh gets its list of addresses from chef attributes. When you first spin up a cluster, the chef nodes do not exist until chef-client runs successfully on the nodes, so until that happens cluster ssh is blind. If something goes wrong with the first chef run, this makes it very difficult to fix what has gone wrong.

In many cases, if a fog_server is present, it has a better idea of what the ip address for a node really is. We should use the fog_server.public_ip_address as a first option and fall back to chef_node if something goes wrong.

**Comment by howech** [comment]
Cluster ssh now looks to the fog_server first for address information.

**Comment by mrflip** [comment]
This was screwing up on chef 10 -- it expects some dumb instance variable to
exist.

In fixing it for chef 10, I have un-re-fixed the preference for the fog
node's personal ip address by swapping the order of those.  Re-un-un-fixing
this will involve a minor dive into the knife ssh -- so for the moment,
knife ssh will work inconsistently on chef 10 when fog and chef disagree.

flip

On Tue, Jul 12, 2011 at 10:34 AM, howech <
reply@reply.github.com>wrote:

> Currently, cluster ssh gets its list of addresses from chef attributes.
> When you first spin up a cluster, the chef nodes do not exist until
> chef-client runs successfully on the nodes, so until that happens cluster
> ssh is blind. If something goes wrong with the first chef run, this makes it
> very difficult to fix what has gone wrong.
> 
> In many cases, if a fog_server is present, it has a better idea of what the
> ip address for a node really is. We should use the
> fog_server.public_ip_address as a first option and fall back to chef_node if
> something goes wrong.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/43

## 

infochimps.com - discover data
