### ISSUE TITLE
bootstrap doesn't work when there's an elastic_ip

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#48]
bootstrap doesn't work when there's an elastic_ip -- it is applied in time for knife to be surprised by its new IP address.

**Comment by temujin9** [comment]
@mrflip This feels a lot more like a pony than a need: we only bootstrap (IIRC) when we're burning an image, and those don't need elastic_ip. Moving to 'manana'; move back if it should be higher priority.

**Comment by temujin9** [comment]
This need has been covered instead by route53, closing as WONTFIX.
