### ISSUE TITLE
Changing the number of instances in a facet

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#50]
What is the expected behavior of cluster_chef if a cookbook is altered to increase/decrease the number of desired instances and then the cluster_chef client is run?

What, if anything, would need to be changed to allow clients to be removed from a cluster facet and appropriate de-configuration done on configuration that was created to accomodate them?

Is there a command or configuration setting to tell cluster_chef to resize itself?

**Comment by mrflip** [comment]
You can change the cluster size in the clusters/ config file all you want -- it only governs the size on explicit request.
- it tells the launch command how many machines to ensure are running. Launch only launches, it will never shut down.
- recipes might use the cluster size to inform configuration (number of available sockets, for example)
- cluster sync uses it to know what chef nodes to sync.

The `launch` command is idempotent: if there are 3 machines running, and 5 specified in the cluster file, then it will launch two more.  If 5 were running, no machines would be launched. If 6 or more were running, no machines would be launched or killed.

The `kill` command kills only the specified machines, and does not pay attention to the cluster size. Nothing will auto-remove machines; you would explicitly kill the top-N-numbered instances, and then do cluster sync to make sure things are sane.  If the cluster has additional decommission (eg the HDFS of a Hadoop cluster) you have to do that separately.

I'd warmly welcome a patch for a `cluster resize` command that did `launch` `kill` and `sync` as appropriate.

**Comment by pcn** [comment]
What part does sync play in reducing the size of a cluster/facet that kill doesn't take care of (on the way down) or that launch doesn't take care of (on the way up)?

**Comment by mrflip** [comment]
if you have node attributes that depend on the cluster size -- i.e. if
foo-dbserver-1 has MAX_CONNS={size of cluster \* 4}  then in taking a
clustter from 4 machines to 40 machine you will want to knife cluster sync
(updating the node attribute) and reconverge (updating the MAX_CONNS)

flip

On Thu, Sep 29, 2011 at 5:29 PM, pcn <
reply@reply.github.com>wrote:

> What part does sync play in reducing the size of a cluster/facet that kill
> doesn't take care of (on the way down) or that launch doesn't take care of
> (on the way up)?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/50#issuecomment-2243991

## 

infochimps.com - discover data

**Comment by mrflip** [comment]
No command to have it resize itself -- you have to update the
clusters/whatever.rb file.

I'm not sure what you mean by "de-configuration". If you mean "knife would
detect that machine X used to have roles A, B, C due to its presence in the
foo-dbserver facet, and thus would remove roles A, B, C" -- no cluster chef
doesn't do that and probably wouldn't; we would typically trash the machine
and instantiate a new one.

changing the number of instances would only affect the few things that look
for the number:
- the launch scripts, etc, which would simply have a new target to shoot
  for. There's no memory here -- each run just looks to that number to know
  what # of machines to ensure are running.
- any recipes which referred to the node attribute for configuration (some
  of the hadoop recipes, elasticsearch and a few DB recipes that use it to set
  open connections, etc). These would require syncing to the chef server (so
  the appropriate attributes are set) and then re-converging the machine (so
  the attributes are applied in the right configs)

flip

On Mon, Sep 26, 2011 at 5:00 PM, pcn <
reply@reply.github.com>wrote:

> What is the expected behavior of cluster_chef if a cookbook is altered to
> increase/decrease the number of desired instances and then the cluster_chef
> client is run?
> 
> What, if anything, would need to be changed to allow clients to be removed
> from a cluster facet and appropriate de-configuration done on configuration
> that was created to accomodate them?
> 
> Is there a command or configuration setting to tell cluster_chef to resize
> itself?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/50

## 

infochimps.com - discover data

**Comment by mrflip** [comment]
(that is, it updates the already-running machines that have made their
decision based on a now-out-of-date cluster size)

On Thu, Sep 29, 2011 at 6:03 PM, Philip (flip) Kromer
flip@infochimps.comwrote:

> if you have node attributes that depend on the cluster size -- i.e. if
> foo-dbserver-1 has MAX_CONNS={size of cluster \* 4}  then in taking a
> clustter from 4 machines to 40 machine you will want to knife cluster sync
> (updating the node attribute) and reconverge (updating the MAX_CONNS)
> 
> flip
> 
> On Thu, Sep 29, 2011 at 5:29 PM, pcn <
> reply@reply.github.com>wrote:
> 
> > What part does sync play in reducing the size of a cluster/facet that kill
> > doesn't take care of (on the way down) or that launch doesn't take care of
> > (on the way up)?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/infochimps/cluster_chef/issues/50#issuecomment-2243991
> 
> ## 
> 
> infochimps.com - discover data

## 

infochimps.com - discover data

**Comment by pcn** [comment]
By de-configure I guess I'm thinking about services that may be stateful/contain state of others (e.g. rabbitmq or other amqp server) where I may want to tell the service to shut itself down gracefully and only kill itself when it's time.  That hook is probably not a day-1 requirement for us, though, since upgrading such things require more than a deployment.

**Comment by mrflip** [comment]
Things like that are actually best done by the machine itself... I
would make an idempotent script that
- tries to kill all services
- sees if they are indeed dead
- if they are, uses ec2-terminate on itself

flip

On Fri, Sep 30, 2011 at 10:22 AM, pcn
reply@reply.github.com
wrote:

> By de-configure I guess I'm thinking about services that may be stateful/contain state of others (e.g. rabbitmq or other amqp server) where I may want to tell the service to shut itself down gracefully and only kill itself when it's time.  That hook is probably not a day-1 requirement for us, though, since upgrading such things require more than a deployment.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/50#issuecomment-2250698

## 

infochimps.com - discover data

**Comment by pcn** [comment]
From a practical point of view, it seems like a chef client delete is also needed for the cluster-facet-count client as they're being removed.  I noticed that I couldn't re-launch nodes, and found your paste at https://gist.github.com/782409/c5a80eb9fd5a974951dbfc5a07dfe27c6428b9ed.

**Comment by mrflip** [comment]
I cleaned up the code for `knife cluster kill`, making it easier to independently remove any or all of
- chef client key from chef server
- chef node & attributes from server
- terminate machine in cloud.

Closing this issue, but I'd welcome a patch that used the other knife commands to do a resize.
