### ISSUE TITLE
Config files referenced in notes/pt1[...] don't exist

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#51]
notes/pt1-initial-settings-and-credentials.textile mentions:

<pre><code>
  cd PATH/TO/cluster_chef
  cp ./config/poolparty-example.yaml   ~/.hadoop-ec2/poolparty.yaml 
  ln -nfs ~/.hadoop-ec2/poolparty.yaml ~/.hadoop-ec2/aws
  # optional:
  ( cd ~/.hadoop-ec2 && git init && git add . && git commit -m "Initial commit" )
</code></pre>

From the commit history, it looks like poolparty-example.yaml became cluster_chef.yaml, and then removed in/around https://github.com/infochimps/cluster_chef/tree/f88f0830b8b6e1da9f36d4a298e003127165c224/config.  

Should these notes files be removed or updated?

**Comment by mrflip** [comment]
yes, they should be removed.  The docs are due for a cleanup.
