### ISSUE TITLE
config/bootstrap_chef_client.sh.erb relies on runit

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#55]
Runit is required to start chef-client.  Without it, that fails.  It seems that runit is a requirement for most of the cookbooks that you provide, but not for e.g. nfs-server.

Runit should probably just be installed by default.

**Comment by pcn** [comment]
The impact of this is that the demosimple cluster will fail to start the chef client.

**Comment by mrflip** [comment]
This needs cleanup. We've moved to the scripts in `lib/chef/knife/bootstrap`. I'm actually going to nuke the scripts in `config/` as they're well obsolete.

We should review for recipes that are using runit but not `include_recipe` -- look for that in the version_3 branch shortly.
