### ISSUE TITLE
Complex hadoop cluster convergence should be more reliable

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#60]
Cluster convergence of complex hadoop clusters needs to be more solid.

While it would be awesome to have fire-and-forget for a full cluster, orchestrating the convergence and invocation of nearly a dozen services across as many as four supervisory machines is demostrably non-trivial. I'm at peace with a workflow that went something like
- launch namenode, wait for initial chef-client run to complete
- single-command script to format namenode and start services
- launch all remaining nodes
  ... and from there, evaluate full fire-and forget

---
### TODO
- Separate initial chef convergence of configuration from hadoop service launch
  - Cluster recipes give you control over whether to _launch+enable_, _enable_, etc services by default.
  - a single-step mechanism to switch the services on 
  - take another look at the namenode formatting step
- compatibility with CDH3u1 (which dicks around with a few paths).
- cluster_service provider racing
  - When you stop-start machines, or otherwise need to reconverge, this will happily sail through with no notion of the race condition. Add a `knife cluster unprovide` that unregisters to provide all services, and have `knife cluster stop` invoke it along the way.
  - add a `wait_for_provider` helper (or option) -- see fiksu@b65a7a5b74402c0c222ae9da27bd8163045997e8
- checkpoints so that if a service provider is missing (eg namenode not running) it doesn't cause chef to bomb out
- cluster reconvergence when machines are stopped and then started

**Comment by temujin9** [comment]
The orchestration of various start-up and tear-down steps is part of what drove my push for RunDeck. That said, it's intended to be a light-hand, and I wouldn't **mind** the entirety of a hadoop cluster converging on launch, presuming it can be done without a lot of pain.

**Comment by mrflip** [comment]
We're stop/startin' and no-look-launchin' things all over the place. Typical time from "knife cluster launch bonobo-worker" until reporting in the jobtracker is <= 6 minutes on launch, faster than that on start.

Instantiating a cluster from thin air requires
- start the master, with all the `:run_state`s set to 'stop'
- running `/etc/hadoop/conf/bootstrap_hadoop_namenode.sh`, which is now fairly robust and re-runnable. It should start the namenode on its own.
- set `run_state`s to 'start', run `knife cluster sync` and then `knife cluster kick` the master.
- launch the jobbtracker, workers, etc.

**Comment by pcn** [comment]
Is there a cookbook I can look at to get some guidance on how this works now to put the prior update into context?

**Comment by mrflip** [comment]
Added some example clusters -- https://github.com/infochimps-cookbooks/hadoop_cluster/tree/master/example/clusters
