### ISSUE TITLE
knife launch should create a chef node if not present

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#62]
Knife should create the chef node if it's missing.

This causes problems with sync and lots besides when it doesn't

flip

**Comment by temujin9** [comment]
I think there were unresolved permissions issues which prevented this, the last time it was tried by Chris.

**Comment by mrflip** [comment]
Ah, right.

The client that creates the node is the one that then owns it.

It would probably be best if knife force-created the client _and_ the node
on `launch` -- we would also then be pushing in the client.pem and not the
activation.pem, which is much nicer. But also much more complicated, and
something that feels like it should be in knife core. I shall sail the IRCs
and see what @opscode thinks.

Now I remember why this wasn't simple.

**Comment by temujin9** [comment]
Well, if it were simple, we'd have done it already . . . 

I agree that bootstrapping in the pre-made client definition seems more correct than relying on the client to make client and node itself.

**Comment by mrflip** [comment]
this might work:
- ensure the client exists. If it doesn't, make the client on my side, and
  just discard the key.
- ensure the node exists, and ensure that the eponymous client has the right
  permissions.
- when the machine spins up, I _think_ it will just blow away the old client
  key and assume its identity, leaving the permissions alone.

If so, Bob's our uncle.

flip

On Tue, Oct 25, 2011 at 2:36 PM, Nathaniel Eliot <
reply@reply.github.com>wrote:

> Well, if it were easy, we'd have done it already . . .
> 
> I agree that bootstrapping in the pre-made client definition seems more
> correct than relying on the client to make client and node itself.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/infochimps/cluster_chef/issues/62#issuecomment-2521893

## 

infochimps.com - discover data

**Comment by mrflip** [comment]
Fixed.

If the client doesn't exist, knife creates it and saves the client key.
If the node exists, life is good.
If the node doesn't exist, and we have the client key (saved or newly-created), knife creates the node using that client -- making it the owner, life is good.

If the node doesn't exist, and you don't have the client key, knife will error out. You have to delete the client, or create the node yourself and then adjust permissions.

**Comment by temujin9** [comment]
+1
