### ISSUE TITLE
v3 documentation needs to note the new knife plug-in location

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#67]
I'm testing out v3 from the git head via a pull from upstream to my local repo, and I've noticed that the location of the knife plugin has moved in the cluster_chef repo.  Can you update the readme to add:

```
mkdir -p ~/.chef/plugins # probably not necessary, but I'm not 100% sure since I haven't re-built my chef install
cd .chef/plugins && \
ln -s $CLUSTER_CHEF/lib/chef/knife plugins
```

**Comment by pcn** [comment]
I re-set my GEM_HOME and tried installing v3 from a fairly clean slate and it seemed to still require that ~/.chef/plugins/knife symlink to $CLUSTER_CHEF_DIR/lib/chef/knife.  

The instructions make it seem like "bundle install" should do all of the work, but it doesn't appear to cause knife to find the cluster sub-commands.

**Comment by temujin9** [comment]
This appears to be fixed with the gem. If you are still experiencing issues, please reopen this with detailed debug output of the failure.

**Comment by pcn** [comment]
What's the fix?  I can't let my users rely on the gem.  Since I have fixes that haven't gone into the gem and that don't appear to be on-track at the moment, I'm afraid that the method for _not_ installing as a gem may bit-rot.
