### ISSUE TITLE
What permissions need to be set to use hosted chef with v3

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#68]
I'm getting 403 errors from opscode when creating clients.  I noticed that you had a 500 error last week (http://help.opscode.com/discussions/problems/866-opscode-platform-500-error-creating-chef-client-with-site-or-with-knife) but I think this is different.

Based on this: http://help.opscode.com/discussions/problems/873-how-can-i-find-out-what-permission-is-being-denied it looks like the v3 client creation needs to do some more work on the knife side... maybe?  I'm trying to knife from a cluster definition and all of my clients end up seeing this stack trace when running chef-client --once

Generated at Tue Nov 08 21:54:17 +0000 2011
Net::HTTPServerException: 403 "Forbidden"
/usr/lib/ruby/1.8/net/http.rb:2105:in `error!'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:237:in`api_request'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:288:in `retriable_rest_request'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:218:in`api_request'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:130:in `put_rest'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/api_client.rb:247:in`save'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:81:in `register'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:79:in`upto'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:79:in `register'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:77:in`catch'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/rest.rb:77:in `register'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/client.rb:280:in`register'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/client.rb:150:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/client.rb:239:in`run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/client.rb:229:in `loop'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/client.rb:229:in`run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application.rb:67:in `run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/chef-client:26
/usr/bin/chef-client:19:in`load'
/usr/bin/chef-client:19

What are you doing to prevent this when you test?

**Comment by temujin9** [comment]
Flip did a lot of work on the stack these last few weeks, including cleaning up the way clients are created; you might have gotten one of the unstable commits. Can you verify whether you're still having the permission issues you saw?

**Comment by pcn** [comment]
I'll try again over the next couple of days.
