### ISSUE TITLE
Rundeck integration: cookbooks and tools into mainline cluster_chef

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#72]
!Reminder to Nate!

Per conversations today, opening this to track the release of Nate's rundeck cookbook.

I'd like to help work on the DSL to allow services to wait for a resource/be orchestrated by rundeck.

**Comment by pcn** [comment]
Pinging on this.  Is there anything I can do to help here?

**Comment by pcn** [comment]
Any word on the rundeck cookbook?

**Comment by pcn** [comment]
Any word on whether rundeck is proving useful when ordering deployments?  Should i ignore this and start adding loops around discover() calls and come back later?

Thanks!

**Comment by temujin9** [comment]
It looks like finalizing Rundeck is on our longer-term roadmap. For the moment, I would recommend using your discover() looping method instead.

**Comment by temujin9** [comment]
(@aseever - @dhruvbansal had been asking if he could pick this up, which I would wholly support, as having it will open several other doors in addition to the one he wants it for.)
