### ISSUE TITLE
cluster_chef tools launch vagrant instances

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#75]
Cluster chef should launch vagrants just as well as ec2 instances:
1. Create/Update `Vagrantfile`s into persistent (versionable) directory tree
2. `Vagrantfile`s should come from a (configurable) `.erb` template
3. Goal should be that any reasonable cluster file works with no changes (apart from hints in its `cloud` block) on vagrant vs. ec2.
#### Notes:
- this should pretty well clarify #66 (`cloud` keyword FTL) and show the way towards #28 (cloud agnostic)
- Initial effort should assume a chef server exists, as the discovery features etc are pretty lame without them. We can get less opinionate later.
#### Same/Alternate Universes

The only near-term internal need for VMs at infochimps is testing/development: we want to be able to define a "foobar" cluster, run it a bunch of times as VMs (ensuring that it does NOT interact with the production machines, which live in the EC2 cloud), then throw a switch and deploy it to the cloud. VM launches should thus be isolated but behave as closely as possible to their eventual cloud selves.

So a person might argue that we should have one true chef server, do something like prefix cluster names with `vm_` to mark them as second-class citizens, and in other ways use code + convention to hold them semi-isolated. However: 
- when I look at the chef server, I'll see nodes that I have no access to.
- If two people are stunting the same cluster on their own machines they'll collide on the chef server
- I predict this will lead to conditional code in all sorts of wrong places
- there would be no way to use production VMs.
- the phrase "semi-isolated" reads to me as "yeah, until you find out it isn't".

I think the right plan is the One Incestuous Family plan:
- VMs in same chef server are all held equal.
- Clusters have a preferred cloud, but launching some eg. cassandra nodes as VMs and some as cloud nodes is totally fine -- they'll try to discover each other, and once discovered will start pulling in shards. This accomodates people using VMs in production environments, and terrifies people using VMs for testing purposes.
- For our use case VMs and cloud machines are held truly isolated by giving each their own chef server. To discover cloud state (eg have them hook up to a staging DB), we mirror those nodes' metadata to the stunt VM chef server.
- We let you munge the chef Environment name with the cloud name. Say EC2 is my primary cloud, and my cluster file declares `environment(:prod)`. When I launch an EC2 server, it is placed into the `prod` Environment; when I launch a VM it is placed into the `vm_prod` environment. This gives you some ability to isolate/tailor VM instances in a shared universe. For our purposes, this would let us cripple any VM that somehow found its way to the production chef server.

**Comment by temujin9** [comment]
If VMs are for testing/development only, they should be either in environment(:dev) or environment(:vagrant). My preference would be the latter (name doesn't matter - :vm_dev would also work), as we will probably find numerous things that require slight differences for a VM cluster.

For preventing stunt cluster collision, I propose all vagrants be forced (by convention, not code) to a cluster name of either username.to_sym or hostname.to_sym. Stunting a cluster of the same name as an existing cluster should be a definite no-no, maybe enforced by code (if that's easy).

I can't envision a scenario where we will want vagrants in staging or production, and I think it's okay for cluster_chef to be opinionated about that. If you are going to be :stag or :prod, you must use a VM some sort of stable environment that is globally addressable. That can be a Vagrant server (if you're getting silly), but it has to be one living in a server room.

**Comment by mrflip** [comment]
The major work here is in place; the remaining step is to integrate it with the normal knife cluster launch etc commands, which will happen when we refactor the cloud support. closing.
