### ISSUE TITLE
knife cluster kick should launch chef-client directly if service is not running

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#76]
currently `knife cluster kick` ssh's in and sends a -QUIT signal to the service, causing it to run immediately.  If the service isn't running, however, it causes an opaque error message lost in the deluge of log lines that ensue from the other clients.

kcik should first do a `service chef-client status` command, and if the service is not running it should just run chef-client directly.

**Comment by temujin9** [comment]
+1: we don't want to be bound to a world where the client must be running its polling loop

**Comment by pcn** [comment]
For my own use, I've done a less-elegant way and added the flag "--once" to the kick command.  This says (to me) "run chef-client --once".  I like the idea of discovery better, but this is just a simpler shell script to send to the client.
