### ISSUE TITLE
lib/cluster_chef/discovery.rb crashes when the node doesn't exist but the client does

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#77]
I'm trying to use the version_3 branch, and I'm running into this issue:

<pre>
    /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/api_client.rb:166:in `json_create': undefined method `[]' for #<Chef::ApiClient:0x1054c1b60> (NoMethodError)
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/discovery.rb:18:in `chef_clients'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/search/query.rb:44:in `call'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/search/query.rb:44:in `search'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/search/query.rb:44:in `each'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/search/query.rb:44:in `search'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/discovery.rb:16:in `chef_clients'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/discovery.rb:25:in `find_client'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/chef_layer.rb:49:in `chef_client'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/chef_layer.rb:115:in `client_key'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/server.rb:132:in `resolve!'
            from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `to_proc'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/server_slice.rb:23:in `each'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/server_slice.rb:23:in `each'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/facet.rb:109:in `resolve!'
            from /opt/local/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:31:in `to_proc'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/cluster.rb:98:in `each'
            from /Users/pn/new-gems/gems/cluster_chef-3.0.2/lib/cluster_chef/cluster.rb:98:in `resolve!'
            from /Users/pn/.chef/plugins/knife/knife_common.rb:38:in `get_slice'
            from /Users/pn/.chef/plugins/knife/cluster_launch.rb:70:in `run'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/knife.rb:391:in `run_with_pretty_exceptions'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/knife.rb:166:in `run'
            from /Users/pn/new-gems/gems/chef-0.10.4/lib/chef/application/knife.rb:128:in `run'
            from /Users/pn/new-gems/gems/chef-0.10.4/bin/knife:25
            from /Users/pn/new-gems/bin/knife:19:in `load'
            from /Users/pn/new-gems/bin/knife:19
</pre>

printing out the contents of client_hsh at discovery.rb gives me this:

<pre>

#<Chef::ApiClient:0x105cc1d10 @public_key=nil, @index_id=nil, @couchdb=#<Chef::CouchDB:0x105cc1c70 @db="chef", @rest=#<Chef::REST:0x105cc1bf8 @cookies={}, @sign_request=true, @url="http://localhost:5984", @sign_on_redirect=true, @default_headers={}, @redirect_limit=10, @redirects_followed=0, @auth_credentials=#<Chef::REST::AuthCredentials:0x105cc1b58 @client_name=nil, @key_file=nil>>>, @name="StagingCluster-kbs_PlatformAssessment-0", @admin=false, @couchdb_id=nil, @private_key=nil, @couchdb_rev=nil>
</pre>

If I manually delete the client (knife client delete StagingCluster-kbs_PlatformAssessment-0) then I can use chef again.

This may only be a problem when upgrading and subsequently trying to bootstrap.  Could it be caught and some defensive maneuvering be done to prevent crashing into a stack trace?

**Comment by temujin9** [comment]
Having a client without an associated node (or underlying cloud VM) is an inconsistent state in cluster_chef v3, and one that **should** be impossible to achieve using just the knife commands (assuming they work exactly as designed). I think the correct way to address this is to rescue that error and raise another with a clearer description of the error, and the way to fix it. Our remediation for the times this has happened during dev is to 'knife cluster delete' the offending server(s), which also clears out any spurious clients and nodes.

Flip: any thoughts?

**Comment by pcn** [comment]
I've been using a script that deletes nodes and clients that are not associated with an active instance.  Since this script parses the output of the cluster status command, it'd be nicer to have this as a knife cluster clean command to reap instances that, if they're to be re-vivified, need to have artifacts at the chef server removed anyway.

I'm getting pretty lost at times, but this is a low priority since the crude fix I've got is the fix.

**Comment by pcn** [comment]
Less important now that I've changed some of my usage patterns.  Closing for now, will look at again with a rescue if I find it happens again.
