### ISSUE TITLE
It looks like chef-client is setup to use runit, but not service?

### ISSUE THREAD

**Issue by pcn** [infochimps-labs/ironfan#84]
Are you not having failures to complete the bootstrap script like this:

> ec2-50-17-110-208.compute-1.amazonaws.com ***_ec2-50-17-110-208.compute-1.amazonaws.com ***_ Creating chef client script:ec2-50-17-110-208.compute-1.amazonaws.com ***_ec2-50-17-110-208.compute-1.amazonaws.comec2-50-17-110-208.compute-1.amazonaws.com Fri Dec 16 20:08:30 UTC 2011ec2-50-17-110-208.compute-1.amazonaws.com
> ec2-50-17-110-208.compute-1.amazonaws.com ***_ec2-50-17-110-208.compute-1.amazonaws.com ***\* Adding chef client runit scripts: ec2-50-17-110-208.compute-1.amazonaws.com ****
> ec2-50-17-110-208.compute-1.amazonaws.comec2-50-17-110-208.compute-1.amazonaws.com fail: chef-client: unable to change to service directory: file does not existec2-50-17-110-208.compute-1.amazonaws.com Chef bootstrap failed!

It seems like this needs to be run before service is invoked:

> update-service -a /etc/service chef-client

so that runit will manage chef-client as a service.

Or am I missing something here?

**Comment by temujin9** [comment]
I haven't had replication of this bug internally; chef-client is installed and running on every server I've spun up. Can you confirm whether this is still occurring?

**Comment by pcn** [comment]
I'm pretty sure it still exists.  I've changed my bootstrap scripts to loop for a few times with a few seconds worth of sleeping to avoid this.

I do this:

``` bash
chmod +x  /etc/sv/chef-client/log/run /etc/sv/chef-client/run
ln -nfs /usr/bin/sv /etc/init.d/chef-client
update-service -a /etc/sv/chef-client chef-client
( for count in 1 2 3 4 5 6 7 8 ; do 
    echo "Trying to stop chef-client, cycle ${count}"
    # runit sleeps for up to 5 seconds, so being able to sleep longer than that
    # will ensure that the service files, etc. are created
    _rv=$(service chef-client stop >/dev/null 2>&1 ; echo $?)
    [ "$_rv" == "0" ] && break
    sleep 2 # should sleep between 1 and 2 seconds
  done
) 
```

**Comment by temujin9** [comment]
I'm not able to replicate this internally, nobody else has chimed in with a similar problem, and you have a workaround which is apparently fixing the problem (or now unnecessary but harmless). Closing this as WONTFIX for now; feel free to reopen if you find it causing further problems.
