### ISSUE TITLE
Behavior of :last in clusters file doesn't match contract

### ISSUE THREAD

**Issue by temujin9** [infochimps-labs/ironfan#94]
The :last keyword doesn't actually push a runlist item to the end.

Reference the nikko cluster for an example: "role[infochimps_final]" (defined at the cluster level, as :last) should be the final item in the runlist, but "role[nikko_stream]" ends up last.

**Comment by mrflip** [comment]
That's because the `nikko_stream` role is added with :last. The facet initializer calls `create_facet_role` which in turn calls `role(@facet_role_name, :last)` -- and similarly for the cluster.

It''s important to make the `facet_role` and `cluster_role` be `:last` as they are typically overrides to everything else. It also seems like a good idea to give them a stable chronology. 

What do you have that should not precede the facet role or cluster role?

**Comment by temujin9** [comment]
I have a couple of things I would like to place after the facet role, but declare in the cluster role. The current candidates are the zabbix and rundeck client definitions, but I'd like to maintain the operational flexibility to experiment with putting other things afterward. Forcing the facet and cluster roles to be :last removes that flexibility, and violates the contract I had understood to be offered with :last.

**Comment by mrflip** [comment]
Here is the current order of things; please arrange them as you would instead prefer:

```
 :first roles def'd in cluster
 :first roles def'd in facet
 normal roles def'd in cluster
 normal roles def'd in facet
 cluster_role (which is a :last role)
 :last roles defined in cluster
 facet role (which is a :last role)
 :last roles defined in facet
```

**Comment by temujin9** [comment]
```
:first roles def'd in cluster
:first roles def'd in facet
normal roles def'd in cluster
cluster_role
normal roles def'd in facet
facet_role
:last roles defined in cluster
:last roles defined in facet
```

**Comment by mrflip** [comment]
I feel like we should be writing these down on slips of paper and sliding them dissolutely across the korsi at some hookah joint on the outskirts of Esfahan.

I like knowing that the cluster role and facet role will act as overrides for everything that isn't `:last`. Would you accept 

```
:first roles def'd in cluster
:first roles def'd in facet
normal roles def'd in cluster
normal roles def'd in facet
cluster_role
facet_role
:last roles defined in cluster
:last roles defined in facet
```

If that's acceptable I can have a fix tout de sweet.

**Comment by temujin9** [comment]
(Ah, excellent effendi. Perhaps a game of ifranjiah will provide some diversion from the strain of negotiation in such climes?)

It's a little harder to explain succinctly, but if that's easier to accomplish and feels acceptable to you, it'll work for me.
