### ISSUE TITLE
Flume master should not announce as a zookeeper

### ISSUE THREAD

**Issue by mrflip** [infochimps-labs/ironfan#98]
If you don't specify an external ZK, Flume master embeds a zk inside itself listening on the usual port.  The flume cookbook as written needs to discover a zk in order to write configuration data.

Thus, the current flume cookbook announces as a zookeeper: e76df576f612a7 / https://github.com/infochimps/infochimps_homebase/blob/e76df576f612a7a514e2658b95227c99346470f6/vendor/infochimps/flume/recipes/master.rb#L34

Proposed:
- If there is no external zookeeper, the flume master should announce as a 'zookeeper-flume_internal'.
- Flume workers should discover 'zookeeper-server' and if none is present discover 'zookeeper-flume_internal'

@kornypoet @dhruvbansal

**Comment by temujin9** [comment]
This announcement is no longer in recipes/master.rb. I'm assuming for now that this was made to work with another system, and closing this issue.
